//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Cvm) DeepCopyInto(out *Cvm) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Cvm.
func (in *Cvm) DeepCopy() *Cvm {
	if in == nil {
		return nil
	}
	out := new(Cvm)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Cvm) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CvmList) DeepCopyInto(out *CvmList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Cvm, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CvmList.
func (in *CvmList) DeepCopy() *CvmList {
	if in == nil {
		return nil
	}
	out := new(CvmList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CvmList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CvmOrder) DeepCopyInto(out *CvmOrder) {
	*out = *in
	if in.Resource != nil {
		in, out := &in.Resource, &out.Resource
		*out = new(CvmResource)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CvmOrder.
func (in *CvmOrder) DeepCopy() *CvmOrder {
	if in == nil {
		return nil
	}
	out := new(CvmOrder)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CvmResource) DeepCopyInto(out *CvmResource) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CvmResource.
func (in *CvmResource) DeepCopy() *CvmResource {
	if in == nil {
		return nil
	}
	out := new(CvmResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CvmSpec) DeepCopyInto(out *CvmSpec) {
	*out = *in
	out.Workload = in.Workload
	if in.UserResource != nil {
		in, out := &in.UserResource, &out.UserResource
		*out = new(CvmResource)
		**out = **in
	}
	if in.PurchasedResource != nil {
		in, out := &in.PurchasedResource, &out.PurchasedResource
		*out = new(CvmResource)
		**out = **in
	}
	if in.PendingPurchasedResource != nil {
		in, out := &in.PendingPurchasedResource, &out.PendingPurchasedResource
		*out = new(CvmResource)
		**out = **in
	}
	if in.BaseOrder != nil {
		in, out := &in.BaseOrder, &out.BaseOrder
		*out = new(CvmOrder)
		(*in).DeepCopyInto(*out)
	}
	if in.ExpandOrder != nil {
		in, out := &in.ExpandOrder, &out.ExpandOrder
		*out = new(CvmOrder)
		(*in).DeepCopyInto(*out)
	}
	if in.RenewOrder != nil {
		in, out := &in.RenewOrder, &out.RenewOrder
		*out = new(CvmOrder)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CvmSpec.
func (in *CvmSpec) DeepCopy() *CvmSpec {
	if in == nil {
		return nil
	}
	out := new(CvmSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CvmStatus) DeepCopyInto(out *CvmStatus) {
	*out = *in
	if in.EffectiveResource != nil {
		in, out := &in.EffectiveResource, &out.EffectiveResource
		*out = new(CvmResource)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CvmStatus.
func (in *CvmStatus) DeepCopy() *CvmStatus {
	if in == nil {
		return nil
	}
	out := new(CvmStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Workload) DeepCopyInto(out *Workload) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Workload.
func (in *Workload) DeepCopy() *Workload {
	if in == nil {
		return nil
	}
	out := new(Workload)
	in.DeepCopyInto(out)
	return out
}
