apiVersion: w7panel.w7.com/v1alpha1
kind: Permission
metadata:
  name: k3k.permission.normal
  labels:
    typemode: in
spec:
  title: 普通用户
  type: builtin
  role: normal
  menu: []
  api:
    /panel-api/v1/k3k/info:
    - get
    /panel-api/v1/auth/userinfo:
    - get
    /panel-api/v1/auth/console/info:
    - get
    /panel-api/v1/auth/refresh-token2:
    - create
    /panel-api/v1/microapp/*:
    - get
    /panel-api/v1/microapp/*/proxy/*:
    - '*'
    /panel-api/v1/namespaces/*/services/*/proxy/*:
    - '*'
    /panel-api/v1/namespaces/*/pods/*/proxy/*:
    - '*'
  features:
    debug: false
    fileeditor: false
    webshell: false
  rbacRules: []
