kind: ConfigMap
apiVersion: v1
metadata:
    name: k3k.permission.tech
    namespace: default
    labels:
        clustermode: global
        type: permission
        typemode : in
    annotations:
        title: 技术人员
        #w7.cc/domain-white-list: '[]'
data:
    debug: "false"
    fileeditor: "false"
    menu: >-
        ["cluster","cluster-panel","cluster-resource","app","app-apps","app-apps-add","app-apps-edit","app-apps-delete","app-cronjob","app-cronjob-add","app-cronjob-edit","app-cronjob-delete","app-rvproxy","app-rvproxy-add","app-rvproxy-edit","app-rvproxy-delete","app-dblist","app-dblist-add","app-dblist-delete","app-gpustack","storage","storage-node","storage-node-add","storage-node-edit","storage-node-delete","storage-zone","system","system-cloud","system-order-center","system-cost-center","system-license"]
    webshell: "false"
