kind: ConfigMap
apiVersion: v1
metadata:
    name: k3k.permission.tech
    namespace: default
    labels:
        clustermode: global
        type: permission
        typemode : in
    annotations:
        title: 技术人员
        #w7.cc/domain-white-list: '[]'
data:
    debug: "false"
    fileeditor: "false"
    menu: >-
        ["cluster","cluster/panel","cluster/resource","app","app/apps","app/apps/add","app/apps/edit","app/apps/delete","app/cronjob","app/cronjob/add","app/cronjob/edit","app/cronjob/delete","app/rvproxy","app/rvproxy/add","app/rvproxy/edit","app/rvproxy/delete","app/database","app/database/add","app/database/delete","app/gpustack","storage","storage/disk","storage/disk/add","storage/disk/edit","storage/disk/delete","storage/zone","system","system/cloud","person/order-center","person/cost-center","system/license"]
    webshell: "false"
