apiVersion: w7panel.w7.com/v1alpha1
kind: Permission
metadata:
  name: k3k.permission.founder
  labels:
    typemode: in
spec:
  title: 创始人
  type: builtin
  role: founder
  menu:
  - '*'
  api:
    '*':
    - '*'
  features:
    debug: true
    fileeditor: true
    webshell: true
  rbacRules:
  - apiGroups:
    - '*'
    resources:
    - '*'
    verbs:
    - '*'
