apiVersion: w7panel.w7.com/v1alpha1
kind: Permission
metadata:
  name: k3k.permission.api
  labels:
    typemode: in
spec:
  title: 对外 API
  type: builtin
  role: api
  menu: []
  api:
    /panel-api/v1/auth/userinfo:
    - get
    /panel-api/v1/auth/refresh-token2:
    - create
    /panel-api/v1/userinfo:
    - get
    /panel-api/v1/menu:
    - get
    /panel-api/v1/k3k/info:
    - get
    /panel-api/v1/k3k/cvm*:
    - '*'
    /panel-api/v1/k3k/ckm*:
    - '*'
    /panel-api/v1/k3k/overselling/*:
    - '*'
    /panel-api/v1/k3k/order/license:
    - create
    /panel-api/v1/namespaces:
    - get
    /panel-api/v1/helm/*:
    - '*'
    /panel-api/v1/zpk/*:
    - '*'
    /panel-api/v1/metrics/*:
    - get
    /panel-api/v1/audit/*:
    - get
    /panel-api/v1/gpu/*:
    - '*'
    /panel-api/v1/registry/*:
    - '*'
    /panel-api/v1/tty:
    - get
    /panel-api/v1/nodetty:
    - get
    /panel-api/v1/exec:
    - get
    /panel-api/v1/exec2:
    - create
    /panel-api/v1/exec-all:
    - create
    /panel-api/v1/download/*:
    - get
    /panel-api/v1/files/*:
    - '*'
    /panel-api/v1/cp:
    - create
    /panel-api/v1/cppid:
    - create
    /panel-api/v1/mvpid:
    - create
    /panel-api/v1/pid:
    - get
    /panel-api/v1/nodepid:
    - get
    /panel-api/v1/mountfiles*:
    - '*'
    /panel-api/v1/yaml:
    - create
    /panel-api/v1/rollback:
    - update
    /panel-api/v1/kcompose:
    - create
    /panel-api/v1/pinyin:
    - create
    /panel-api/v1/dns*:
    - '*'
    /panel-api/v1/myip:
    - get
    /panel-api/v1/db-conn-test:
    - create
    /panel-api/v1/ping-etcd:
    - create
    /panel-api/v1/*/proxy/*:
    - '*'
    /panel-api/v1/namespaces/*/services/*/proxy-root/*:
    - '*'
    /panel-api/v1/namespaces/*/services/*/proxy/*:
    - '*'
    /panel-api/v1/namespaces/*/pods/*/proxy/*:
    - '*'
    /panel-api/v1/longhorn/*:
    - '*'
    /panel-api/v1/static/*:
    - '*'
    /panel-api/v1/kubeconfig:
    - get
    /panel-api/v1/s3bucket:
    - '*'
    /panel-api/v1/microapp/*:
    - '*'
    /panel-api/v1/containers/*:
    - '*'
    /panel-api/v1/oidc/*:
    - '*'
    /panel-api/v1/code:
    - create
    /panel-api/v1/callback-url:
    - create
  features:
    debug: true
    fileeditor: true
    webshell: true
  rbacRules:
  - apiGroups:
    - apiextensions.k8s.io
    resources:
    - customresourcedefinitions
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - ''
    resources:
    - namespaces
    - serviceaccounts
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - w7panel.w7.com
    resources:
    - '*'
    verbs:
    - get
    - list
    - watch
