kind: ConfigMap
apiVersion: v1
metadata:
    name: k3k.permission.normal
    namespace: default
    labels:
        clustermode: global
        type: permission
        typemode : in
    annotations:
        title: 普通用户
        #w7.cc/domain-white-list: '[]'
data:
    debug: "false"
    fileeditor: "false"
    menu: >-
        []
    webshell: "false"
