apiVersion: w7panel.w7.com/v1alpha1
kind: Permission
metadata:
    labels:
        typemode: in
    name: normal
spec:
    apiRules:
        -
            method:
                - get
            path: /panel-api/v1/auth/userinfo
        -
            method:
                - get
            path: /panel-api/v1/auth/console/info
        -
            method:
                - create
            path: /panel-api/v1/auth/refresh-token2
        -
            method:
                - get
            path: /panel-api/v1/k3k/info
        -
            method:
                - create
            path: /panel-api/v1/k3k/sync-down-static
        -
            method:
                - get
            path: /panel-api/v1/metrics/state
        -
            method:
                - get
            path: /panel-api/v1/metrics/usage/cvm/*/name/*/disk
        -
            method:
                - get
            path: /panel-api/v1/metrics/usage/cvm/*/name/*/normal
        -
            method:
                - get
            path: /panel-api/v1/metrics/usage/disk
        -
            method:
                - get
            path: /panel-api/v1/metrics/usage/normal
        -
            method:
                - get
            path: /panel-api/v1/microapp/*/frontprops
        -
            method:
                - get
            path: /panel-api/v1/microapp/*/info
        -
            method:
                - delete
                - get
                - patch
                - create
                - update
            path: /panel-api/v1/microapp/*/proxy/*
        -
            method:
                - get
            path: /panel-api/v1/microapp/top
        -
            method:
                - create
            path: /panel-api/v1/oidc/js-code
        -
            method:
                - create
            path: /panel-api/v1/static/*/download/*
        -
            method:
                - get
            path: /panel-api/v1/static/*/status
        -
            method:
                - get
            path: /panel-api/v1/static/proxy/*
        -
            method:
                - get
            path: /panel-api/v1/namespaces/*/services/*/proxy/*
        -
            method:
                - create
            path: /panel-api/v1/namespaces/*/pods/*/proxy/*
    domainWhiteList: []
    features:
        debug: false
        fileeditor: false
        webshell: false
    menuRules: []
    parentPermission: ''
    role: normal
    title: 普通用户
    type: builtin
