/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	microappsettingv1alpha1 "github.com/w7panel/w7panel/k8s/pkg/apis/microappsetting/v1alpha1"
	applyconfigurationmicroappsettingv1alpha1 "github.com/w7panel/w7panel/k8s/pkg/client/microappsetting/applyconfiguration/microappsetting/v1alpha1"
	scheme "github.com/w7panel/w7panel/k8s/pkg/client/microappsetting/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// MicroAppSettingsGetter has a method to return a MicroAppSettingInterface.
// A group's client should implement this interface.
type MicroAppSettingsGetter interface {
	MicroAppSettings(namespace string) MicroAppSettingInterface
}

// MicroAppSettingInterface has methods to work with MicroAppSetting resources.
type MicroAppSettingInterface interface {
	Create(ctx context.Context, microAppSetting *microappsettingv1alpha1.MicroAppSetting, opts v1.CreateOptions) (*microappsettingv1alpha1.MicroAppSetting, error)
	Update(ctx context.Context, microAppSetting *microappsettingv1alpha1.MicroAppSetting, opts v1.UpdateOptions) (*microappsettingv1alpha1.MicroAppSetting, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*microappsettingv1alpha1.MicroAppSetting, error)
	List(ctx context.Context, opts v1.ListOptions) (*microappsettingv1alpha1.MicroAppSettingList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *microappsettingv1alpha1.MicroAppSetting, err error)
	Apply(ctx context.Context, microAppSetting *applyconfigurationmicroappsettingv1alpha1.MicroAppSettingApplyConfiguration, opts v1.ApplyOptions) (result *microappsettingv1alpha1.MicroAppSetting, err error)
	MicroAppSettingExpansion
}

// microAppSettings implements MicroAppSettingInterface
type microAppSettings struct {
	*gentype.ClientWithListAndApply[*microappsettingv1alpha1.MicroAppSetting, *microappsettingv1alpha1.MicroAppSettingList, *applyconfigurationmicroappsettingv1alpha1.MicroAppSettingApplyConfiguration]
}

// newMicroAppSettings returns a MicroAppSettings
func newMicroAppSettings(c *W7panelV1alpha1Client, namespace string) *microAppSettings {
	return &microAppSettings{
		gentype.NewClientWithListAndApply[*microappsettingv1alpha1.MicroAppSetting, *microappsettingv1alpha1.MicroAppSettingList, *applyconfigurationmicroappsettingv1alpha1.MicroAppSettingApplyConfiguration](
			"microappsettings",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *microappsettingv1alpha1.MicroAppSetting { return &microappsettingv1alpha1.MicroAppSetting{} },
			func() *microappsettingv1alpha1.MicroAppSettingList {
				return &microappsettingv1alpha1.MicroAppSettingList{}
			},
		),
	}
}
