//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigMapRef) DeepCopyInto(out *ConfigMapRef) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigMapRef.
func (in *ConfigMapRef) DeepCopy() *ConfigMapRef {
	if in == nil {
		return nil
	}
	out := new(ConfigMapRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FilingSettings) DeepCopyInto(out *FilingSettings) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FilingSettings.
func (in *FilingSettings) DeepCopy() *FilingSettings {
	if in == nil {
		return nil
	}
	out := new(FilingSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GeneralSettings) DeepCopyInto(out *GeneralSettings) {
	*out = *in
	out.SiteLogo = in.SiteLogo
	out.Filing = in.Filing
	if in.ContactConfigs != nil {
		in, out := &in.ContactConfigs, &out.ContactConfigs
		*out = make([]ContactConfigSettings, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GeneralSettings.
func (in *GeneralSettings) DeepCopy() *GeneralSettings {
	if in == nil {
		return nil
	}
	out := new(GeneralSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoginSettings) DeepCopyInto(out *LoginSettings) {
	*out = *in
	out.ProtocolConfig = in.ProtocolConfig
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoginSettings.
func (in *LoginSettings) DeepCopy() *LoginSettings {
	if in == nil {
		return nil
	}
	out := new(LoginSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MicroAppSetting) DeepCopyInto(out *MicroAppSetting) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MicroAppSetting.
func (in *MicroAppSetting) DeepCopy() *MicroAppSetting {
	if in == nil {
		return nil
	}
	out := new(MicroAppSetting)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MicroAppSetting) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MicroAppSettingList) DeepCopyInto(out *MicroAppSettingList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MicroAppSetting, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MicroAppSettingList.
func (in *MicroAppSettingList) DeepCopy() *MicroAppSettingList {
	if in == nil {
		return nil
	}
	out := new(MicroAppSettingList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MicroAppSettingList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MicroAppSettingSpec) DeepCopyInto(out *MicroAppSettingSpec) {
	*out = *in
	out.Login = in.Login
	out.General = in.General
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MicroAppSettingSpec.
func (in *MicroAppSettingSpec) DeepCopy() *MicroAppSettingSpec {
	if in == nil {
		return nil
	}
	out := new(MicroAppSettingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProtocolConfig) DeepCopyInto(out *ProtocolConfig) {
	*out = *in
	out.UserAgreement = in.UserAgreement
	out.PrivacyPolicy = in.PrivacyPolicy
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProtocolConfig.
func (in *ProtocolConfig) DeepCopy() *ProtocolConfig {
	if in == nil {
		return nil
	}
	out := new(ProtocolConfig)
	in.DeepCopyInto(out)
	return out
}
