/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	buildimagev1alpha1 "github.com/w7panel/w7panel/k8s/pkg/apis/buildimage/v1alpha1"
	applyconfigurationbuildimagev1alpha1 "github.com/w7panel/w7panel/k8s/pkg/client/buildimage/applyconfiguration/buildimage/v1alpha1"
	scheme "github.com/w7panel/w7panel/k8s/pkg/client/buildimage/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// BuildImagesGetter has a method to return a BuildImageInterface.
// A group's client should implement this interface.
type BuildImagesGetter interface {
	BuildImages(namespace string) BuildImageInterface
}

// BuildImageInterface has methods to work with BuildImage resources.
type BuildImageInterface interface {
	Create(ctx context.Context, buildImage *buildimagev1alpha1.BuildImage, opts v1.CreateOptions) (*buildimagev1alpha1.BuildImage, error)
	Update(ctx context.Context, buildImage *buildimagev1alpha1.BuildImage, opts v1.UpdateOptions) (*buildimagev1alpha1.BuildImage, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*buildimagev1alpha1.BuildImage, error)
	List(ctx context.Context, opts v1.ListOptions) (*buildimagev1alpha1.BuildImageList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *buildimagev1alpha1.BuildImage, err error)
	Apply(ctx context.Context, buildImage *applyconfigurationbuildimagev1alpha1.BuildImageApplyConfiguration, opts v1.ApplyOptions) (result *buildimagev1alpha1.BuildImage, err error)
	BuildImageExpansion
}

// buildImages implements BuildImageInterface
type buildImages struct {
	*gentype.ClientWithListAndApply[*buildimagev1alpha1.BuildImage, *buildimagev1alpha1.BuildImageList, *applyconfigurationbuildimagev1alpha1.BuildImageApplyConfiguration]
}

// newBuildImages returns a BuildImages
func newBuildImages(c *BuildimageV1alpha1Client, namespace string) *buildImages {
	return &buildImages{
		gentype.NewClientWithListAndApply[*buildimagev1alpha1.BuildImage, *buildimagev1alpha1.BuildImageList, *applyconfigurationbuildimagev1alpha1.BuildImageApplyConfiguration](
			"buildimages",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *buildimagev1alpha1.BuildImage { return &buildimagev1alpha1.BuildImage{} },
			func() *buildimagev1alpha1.BuildImageList { return &buildimagev1alpha1.BuildImageList{} },
		),
	}
}
