//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Ckm) DeepCopyInto(out *Ckm) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Ckm.
func (in *Ckm) DeepCopy() *Ckm {
	if in == nil {
		return nil
	}
	out := new(Ckm)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Ckm) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CkmConsoleOrder) DeepCopyInto(out *CkmConsoleOrder) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CkmConsoleOrder.
func (in *CkmConsoleOrder) DeepCopy() *CkmConsoleOrder {
	if in == nil {
		return nil
	}
	out := new(CkmConsoleOrder)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CkmConsoleOrder) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CkmConsoleOrderList) DeepCopyInto(out *CkmConsoleOrderList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CkmConsoleOrder, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CkmConsoleOrderList.
func (in *CkmConsoleOrderList) DeepCopy() *CkmConsoleOrderList {
	if in == nil {
		return nil
	}
	out := new(CkmConsoleOrderList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CkmConsoleOrderList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CkmConsoleOrderSpec) DeepCopyInto(out *CkmConsoleOrderSpec) {
	*out = *in
	if in.Order != nil {
		in, out := &in.Order, &out.Order
		*out = new(CkmOrder)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CkmConsoleOrderSpec.
func (in *CkmConsoleOrderSpec) DeepCopy() *CkmConsoleOrderSpec {
	if in == nil {
		return nil
	}
	out := new(CkmConsoleOrderSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CkmList) DeepCopyInto(out *CkmList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Ckm, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CkmList.
func (in *CkmList) DeepCopy() *CkmList {
	if in == nil {
		return nil
	}
	out := new(CkmList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CkmList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CkmOrder) DeepCopyInto(out *CkmOrder) {
	*out = *in
	if in.Resource != nil {
		in, out := &in.Resource, &out.Resource
		*out = new(CkmResource)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CkmOrder.
func (in *CkmOrder) DeepCopy() *CkmOrder {
	if in == nil {
		return nil
	}
	out := new(CkmOrder)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CkmResource) DeepCopyInto(out *CkmResource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CkmResource.
func (in *CkmResource) DeepCopy() *CkmResource {
	if in == nil {
		return nil
	}
	out := new(CkmResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CkmSpec) DeepCopyInto(out *CkmSpec) {
	*out = *in
	out.Workload = in.Workload
	if in.UserResource != nil {
		in, out := &in.UserResource, &out.UserResource
		*out = new(CkmResource)
		**out = **in
	}
	if in.PurchasedResource != nil {
		in, out := &in.PurchasedResource, &out.PurchasedResource
		*out = new(CkmResource)
		**out = **in
	}
	if in.PendingPurchasedResource != nil {
		in, out := &in.PendingPurchasedResource, &out.PendingPurchasedResource
		*out = new(CkmResource)
		**out = **in
	}
	if in.BaseOrder != nil {
		in, out := &in.BaseOrder, &out.BaseOrder
		*out = new(CkmOrder)
		(*in).DeepCopyInto(*out)
	}
	if in.ExpandOrder != nil {
		in, out := &in.ExpandOrder, &out.ExpandOrder
		*out = new(CkmOrder)
		(*in).DeepCopyInto(*out)
	}
	if in.RenewOrder != nil {
		in, out := &in.RenewOrder, &out.RenewOrder
		*out = new(CkmOrder)
		(*in).DeepCopyInto(*out)
	}
	if in.ReturnOrders != nil {
		in, out := &in.ReturnOrders, &out.ReturnOrders
		*out = make(map[string]*CkmOrder, len(*in))
		for key, val := range *in {
			var outVal *CkmOrder
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(CkmOrder)
				(*in).DeepCopyInto(*out)
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CkmSpec.
func (in *CkmSpec) DeepCopy() *CkmSpec {
	if in == nil {
		return nil
	}
	out := new(CkmSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CkmStatus) DeepCopyInto(out *CkmStatus) {
	*out = *in
	if in.EffectiveResource != nil {
		in, out := &in.EffectiveResource, &out.EffectiveResource
		*out = new(CkmResource)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.IsExpired != nil {
		in, out := &in.IsExpired, &out.IsExpired
		*out = new(bool)
		**out = **in
	}
	if in.IsRecycling != nil {
		in, out := &in.IsRecycling, &out.IsRecycling
		*out = new(bool)
		**out = **in
	}
	if in.CanBaseBuy != nil {
		in, out := &in.CanBaseBuy, &out.CanBaseBuy
		*out = new(bool)
		**out = **in
	}
	if in.CanExpandBuy != nil {
		in, out := &in.CanExpandBuy, &out.CanExpandBuy
		*out = new(bool)
		**out = **in
	}
	if in.CanRenewBuy != nil {
		in, out := &in.CanRenewBuy, &out.CanRenewBuy
		*out = new(bool)
		**out = **in
	}
	if in.CanDelete != nil {
		in, out := &in.CanDelete, &out.CanDelete
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CkmStatus.
func (in *CkmStatus) DeepCopy() *CkmStatus {
	if in == nil {
		return nil
	}
	out := new(CkmStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Cost) DeepCopyInto(out *Cost) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Cost.
func (in *Cost) DeepCopy() *Cost {
	if in == nil {
		return nil
	}
	out := new(Cost)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Cost) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CostList) DeepCopyInto(out *CostList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Cost, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CostList.
func (in *CostList) DeepCopy() *CostList {
	if in == nil {
		return nil
	}
	out := new(CostList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CostList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CostPackage) DeepCopyInto(out *CostPackage) {
	*out = *in
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = make([]CostPackageItem, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CostPackage.
func (in *CostPackage) DeepCopy() *CostPackage {
	if in == nil {
		return nil
	}
	out := new(CostPackage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CostPackageItem) DeepCopyInto(out *CostPackageItem) {
	*out = *in
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CostPackageItem.
func (in *CostPackageItem) DeepCopy() *CostPackageItem {
	if in == nil {
		return nil
	}
	out := new(CostPackageItem)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CostQuota) DeepCopyInto(out *CostQuota) {
	*out = *in
	if in.Hard != nil {
		in, out := &in.Hard, &out.Hard
		*out = new(CostQuotaHard)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CostQuota.
func (in *CostQuota) DeepCopy() *CostQuota {
	if in == nil {
		return nil
	}
	out := new(CostQuota)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CostQuotaHard) DeepCopyInto(out *CostQuotaHard) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CostQuotaHard.
func (in *CostQuotaHard) DeepCopy() *CostQuotaHard {
	if in == nil {
		return nil
	}
	out := new(CostQuotaHard)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CostSpec) DeepCopyInto(out *CostSpec) {
	*out = *in
	in.CPU.DeepCopyInto(&out.CPU)
	in.Memory.DeepCopyInto(&out.Memory)
	in.Storage.DeepCopyInto(&out.Storage)
	in.Bandwidth.DeepCopyInto(&out.Bandwidth)
	if in.Quota != nil {
		in, out := &in.Quota, &out.Quota
		*out = new(CostQuota)
		(*in).DeepCopyInto(*out)
	}
	if in.Packages != nil {
		in, out := &in.Packages, &out.Packages
		*out = make([]CostPackage, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CostSpec.
func (in *CostSpec) DeepCopy() *CostSpec {
	if in == nil {
		return nil
	}
	out := new(CostSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Workload) DeepCopyInto(out *Workload) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Workload.
func (in *Workload) DeepCopy() *Workload {
	if in == nil {
		return nil
	}
	out := new(Workload)
	in.DeepCopyInto(out)
	return out
}
