//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by deepcopy-gen. DO NOT EDIT.
package v1alpha1

import runtime "k8s.io/apimachinery/pkg/runtime"

func (in *LoginConfig) DeepCopyInto(out *LoginConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}
func (in *LoginConfig) DeepCopy() *LoginConfig {
	if in == nil {
		return nil
	}
	out := new(LoginConfig)
	in.DeepCopyInto(out)
	return out
}
func (in *LoginConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
func (in *LoginConfigList) DeepCopyInto(out *LoginConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]LoginConfig, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&out.Items[i])
		}
	}
}
func (in *LoginConfigList) DeepCopy() *LoginConfigList {
	if in == nil {
		return nil
	}
	out := new(LoginConfigList)
	in.DeepCopyInto(out)
	return out
}
func (in *LoginConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
func (in *LoginConfigSpec) DeepCopyInto(out *LoginConfigSpec) {
	*out = *in
	if in.Providers != nil {
		out.Providers = make([]LoginProvider, len(in.Providers))
		for i := range in.Providers {
			in.Providers[i].DeepCopyInto(&out.Providers[i])
		}
	}
}
func (in *LoginConfigSpec) DeepCopy() *LoginConfigSpec {
	if in == nil {
		return nil
	}
	out := new(LoginConfigSpec)
	in.DeepCopyInto(out)
	return out
}
func (in *LoginProvider) DeepCopyInto(out *LoginProvider) {
	*out = *in
	if in.Scopes != nil {
		out.Scopes = append([]string(nil), in.Scopes...)
	}
}
func (in *LoginProvider) DeepCopy() *LoginProvider {
	if in == nil {
		return nil
	}
	out := new(LoginProvider)
	in.DeepCopyInto(out)
	return out
}
