/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	gpuclassv1alpha1 "github.com/w7panel/w7panel/k8s/pkg/apis/gpuclass/v1alpha1"
	applyconfigurationgpuclassv1alpha1 "github.com/w7panel/w7panel/k8s/pkg/client/gpuclass/applyconfiguration/gpuclass/v1alpha1"
	scheme "github.com/w7panel/w7panel/k8s/pkg/client/gpuclass/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// GpuClassesGetter has a method to return a GpuClassInterface.
// A group's client should implement this interface.
type GpuClassesGetter interface {
	GpuClasses(namespace string) GpuClassInterface
}

// GpuClassInterface has methods to work with GpuClass resources.
type GpuClassInterface interface {
	Create(ctx context.Context, gpuClass *gpuclassv1alpha1.GpuClass, opts v1.CreateOptions) (*gpuclassv1alpha1.GpuClass, error)
	Update(ctx context.Context, gpuClass *gpuclassv1alpha1.GpuClass, opts v1.UpdateOptions) (*gpuclassv1alpha1.GpuClass, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, gpuClass *gpuclassv1alpha1.GpuClass, opts v1.UpdateOptions) (*gpuclassv1alpha1.GpuClass, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*gpuclassv1alpha1.GpuClass, error)
	List(ctx context.Context, opts v1.ListOptions) (*gpuclassv1alpha1.GpuClassList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *gpuclassv1alpha1.GpuClass, err error)
	Apply(ctx context.Context, gpuClass *applyconfigurationgpuclassv1alpha1.GpuClassApplyConfiguration, opts v1.ApplyOptions) (result *gpuclassv1alpha1.GpuClass, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, gpuClass *applyconfigurationgpuclassv1alpha1.GpuClassApplyConfiguration, opts v1.ApplyOptions) (result *gpuclassv1alpha1.GpuClass, err error)
	GpuClassExpansion
}

// gpuClasses implements GpuClassInterface
type gpuClasses struct {
	*gentype.ClientWithListAndApply[*gpuclassv1alpha1.GpuClass, *gpuclassv1alpha1.GpuClassList, *applyconfigurationgpuclassv1alpha1.GpuClassApplyConfiguration]
}

// newGpuClasses returns a GpuClasses
func newGpuClasses(c *GpuclassV1alpha1Client, namespace string) *gpuClasses {
	return &gpuClasses{
		gentype.NewClientWithListAndApply[*gpuclassv1alpha1.GpuClass, *gpuclassv1alpha1.GpuClassList, *applyconfigurationgpuclassv1alpha1.GpuClassApplyConfiguration](
			"gpuclasses",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *gpuclassv1alpha1.GpuClass { return &gpuclassv1alpha1.GpuClass{} },
			func() *gpuclassv1alpha1.GpuClassList { return &gpuclassv1alpha1.GpuClassList{} },
		),
	}
}
