/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	microappv1alpha1 "github.com/w7panel/w7panel/k8s/pkg/apis/microapp/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// MicroAppLister helps list MicroApps.
// All objects returned here must be treated as read-only.
type MicroAppLister interface {
	// List lists all MicroApps in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*microappv1alpha1.MicroApp, err error)
	// MicroApps returns an object that can list and get MicroApps.
	MicroApps(namespace string) MicroAppNamespaceLister
	MicroAppListerExpansion
}

// microAppLister implements the MicroAppLister interface.
type microAppLister struct {
	listers.ResourceIndexer[*microappv1alpha1.MicroApp]
}

// NewMicroAppLister returns a new MicroAppLister.
func NewMicroAppLister(indexer cache.Indexer) MicroAppLister {
	return &microAppLister{listers.New[*microappv1alpha1.MicroApp](indexer, microappv1alpha1.Resource("microapp"))}
}

// MicroApps returns an object that can list and get MicroApps.
func (s *microAppLister) MicroApps(namespace string) MicroAppNamespaceLister {
	return microAppNamespaceLister{listers.NewNamespaced[*microappv1alpha1.MicroApp](s.ResourceIndexer, namespace)}
}

// MicroAppNamespaceLister helps list and get MicroApps.
// All objects returned here must be treated as read-only.
type MicroAppNamespaceLister interface {
	// List lists all MicroApps in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*microappv1alpha1.MicroApp, err error)
	// Get retrieves the MicroApp from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*microappv1alpha1.MicroApp, error)
	MicroAppNamespaceListerExpansion
}

// microAppNamespaceLister implements the MicroAppNamespaceLister
// interface.
type microAppNamespaceLister struct {
	listers.ResourceIndexer[*microappv1alpha1.MicroApp]
}
