/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	buildimagev1alpha1 "github.com/w7panel/w7panel/k8s/pkg/apis/buildimage/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// BuildImageLister helps list BuildImages.
// All objects returned here must be treated as read-only.
type BuildImageLister interface {
	// List lists all BuildImages in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*buildimagev1alpha1.BuildImage, err error)
	// BuildImages returns an object that can list and get BuildImages.
	BuildImages(namespace string) BuildImageNamespaceLister
	BuildImageListerExpansion
}

// buildImageLister implements the BuildImageLister interface.
type buildImageLister struct {
	listers.ResourceIndexer[*buildimagev1alpha1.BuildImage]
}

// NewBuildImageLister returns a new BuildImageLister.
func NewBuildImageLister(indexer cache.Indexer) BuildImageLister {
	return &buildImageLister{listers.New[*buildimagev1alpha1.BuildImage](indexer, buildimagev1alpha1.Resource("buildimage"))}
}

// BuildImages returns an object that can list and get BuildImages.
func (s *buildImageLister) BuildImages(namespace string) BuildImageNamespaceLister {
	return buildImageNamespaceLister{listers.NewNamespaced[*buildimagev1alpha1.BuildImage](s.ResourceIndexer, namespace)}
}

// BuildImageNamespaceLister helps list and get BuildImages.
// All objects returned here must be treated as read-only.
type BuildImageNamespaceLister interface {
	// List lists all BuildImages in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*buildimagev1alpha1.BuildImage, err error)
	// Get retrieves the BuildImage from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*buildimagev1alpha1.BuildImage, error)
	BuildImageNamespaceListerExpansion
}

// buildImageNamespaceLister implements the BuildImageNamespaceLister
// interface.
type buildImageNamespaceLister struct {
	listers.ResourceIndexer[*buildimagev1alpha1.BuildImage]
}
