/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"
	time "time"

	apiscvmv1alpha1 "github.com/w7panel/w7panel/k8s/pkg/apis/cvm/v1alpha1"
	versioned "github.com/w7panel/w7panel/k8s/pkg/client/cvm/clientset/versioned"
	internalinterfaces "github.com/w7panel/w7panel/k8s/pkg/client/cvm/informers/externalversions/internalinterfaces"
	cvmv1alpha1 "github.com/w7panel/w7panel/k8s/pkg/client/cvm/listers/cvm/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// CvmInformer provides access to a shared informer and lister for
// Cvms.
type CvmInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() cvmv1alpha1.CvmLister
}

type cvmInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewCvmInformer constructs a new informer for Cvm type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewCvmInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredCvmInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredCvmInformer constructs a new informer for Cvm type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredCvmInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		cache.ToListWatcherWithWatchListSemantics(&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CvmV1alpha1().Cvms(namespace).List(context.Background(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CvmV1alpha1().Cvms(namespace).Watch(context.Background(), options)
			},
			ListWithContextFunc: func(ctx context.Context, options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CvmV1alpha1().Cvms(namespace).List(ctx, options)
			},
			WatchFuncWithContext: func(ctx context.Context, options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CvmV1alpha1().Cvms(namespace).Watch(ctx, options)
			},
		}, client),
		&apiscvmv1alpha1.Cvm{},
		resyncPeriod,
		indexers,
	)
}

func (f *cvmInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredCvmInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *cvmInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&apiscvmv1alpha1.Cvm{}, f.defaultInformer)
}

func (f *cvmInformer) Lister() cvmv1alpha1.CvmLister {
	return cvmv1alpha1.NewCvmLister(f.Informer().GetIndexer())
}
