/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"
	time "time"

	apisgpuclassv1alpha1 "github.com/w7panel/w7panel/k8s/pkg/apis/gpuclass/v1alpha1"
	versioned "github.com/w7panel/w7panel/k8s/pkg/client/gpuclass/clientset/versioned"
	internalinterfaces "github.com/w7panel/w7panel/k8s/pkg/client/gpuclass/informers/externalversions/internalinterfaces"
	gpuclassv1alpha1 "github.com/w7panel/w7panel/k8s/pkg/client/gpuclass/listers/gpuclass/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// GpuClassInformer provides access to a shared informer and lister for
// GpuClasses.
type GpuClassInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() gpuclassv1alpha1.GpuClassLister
}

type gpuClassInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewGpuClassInformer constructs a new informer for GpuClass type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewGpuClassInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredGpuClassInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredGpuClassInformer constructs a new informer for GpuClass type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredGpuClassInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		cache.ToListWatcherWithWatchListSemantics(&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.GpuclassV1alpha1().GpuClasses(namespace).List(context.Background(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.GpuclassV1alpha1().GpuClasses(namespace).Watch(context.Background(), options)
			},
			ListWithContextFunc: func(ctx context.Context, options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.GpuclassV1alpha1().GpuClasses(namespace).List(ctx, options)
			},
			WatchFuncWithContext: func(ctx context.Context, options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.GpuclassV1alpha1().GpuClasses(namespace).Watch(ctx, options)
			},
		}, client),
		&apisgpuclassv1alpha1.GpuClass{},
		resyncPeriod,
		indexers,
	)
}

func (f *gpuClassInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredGpuClassInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *gpuClassInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&apisgpuclassv1alpha1.GpuClass{}, f.defaultInformer)
}

func (f *gpuClassInformer) Lister() gpuclassv1alpha1.GpuClassLister {
	return gpuclassv1alpha1.NewGpuClassLister(f.Informer().GetIndexer())
}
