//go:build !ignore_autogenerated

package v1alpha1

import (
	rbacv1 "k8s.io/api/rbac/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func (in *ConfigSpec) DeepCopyInto(out *ConfigSpec) {
	*out = *in
	if in.Data != nil {
		in, out := &in.Data, &out.Data
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

func (in *ConfigSpec) DeepCopy() *ConfigSpec {
	if in == nil {
		return nil
	}
	out := new(ConfigSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *K3kConfig) DeepCopyInto(out *K3kConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

func (in *K3kConfig) DeepCopy() *K3kConfig {
	if in == nil {
		return nil
	}
	out := new(K3kConfig)
	in.DeepCopyInto(out)
	return out
}

func (in *K3kConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *K3kConfigList) DeepCopyInto(out *K3kConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]K3kConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *K3kConfigList) DeepCopy() *K3kConfigList {
	if in == nil {
		return nil
	}
	out := new(K3kConfigList)
	in.DeepCopyInto(out)
	return out
}

func (in *K3kConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *K3sConfig) DeepCopyInto(out *K3sConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

func (in *K3sConfig) DeepCopy() *K3sConfig {
	if in == nil {
		return nil
	}
	out := new(K3sConfig)
	in.DeepCopyInto(out)
	return out
}

func (in *K3sConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *K3sConfigList) DeepCopyInto(out *K3sConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]K3sConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *K3sConfigList) DeepCopy() *K3sConfigList {
	if in == nil {
		return nil
	}
	out := new(K3sConfigList)
	in.DeepCopyInto(out)
	return out
}

func (in *K3sConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *License) DeepCopyInto(out *License) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
}

func (in *License) DeepCopy() *License {
	if in == nil {
		return nil
	}
	out := new(License)
	in.DeepCopyInto(out)
	return out
}

func (in *License) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *LicenseList) DeepCopyInto(out *LicenseList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]License, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *LicenseList) DeepCopy() *LicenseList {
	if in == nil {
		return nil
	}
	out := new(LicenseList)
	in.DeepCopyInto(out)
	return out
}

func (in *LicenseList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *LicenseSpec) DeepCopyInto(out *LicenseSpec) {
	*out = *in
}

func (in *LicenseSpec) DeepCopy() *LicenseSpec {
	if in == nil {
		return nil
	}
	out := new(LicenseSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *OverSellingConfig) DeepCopyInto(out *OverSellingConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
}

func (in *OverSellingConfig) DeepCopy() *OverSellingConfig {
	if in == nil {
		return nil
	}
	out := new(OverSellingConfig)
	in.DeepCopyInto(out)
	return out
}

func (in *OverSellingConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *OverSellingConfigList) DeepCopyInto(out *OverSellingConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OverSellingConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *OverSellingConfigList) DeepCopy() *OverSellingConfigList {
	if in == nil {
		return nil
	}
	out := new(OverSellingConfigList)
	in.DeepCopyInto(out)
	return out
}

func (in *OverSellingConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *OverSellingConfigSpec) DeepCopyInto(out *OverSellingConfigSpec) {
	*out = *in
}

func (in *OverSellingConfigSpec) DeepCopy() *OverSellingConfigSpec {
	if in == nil {
		return nil
	}
	out := new(OverSellingConfigSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *Permission) DeepCopyInto(out *Permission) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

func (in *Permission) DeepCopy() *Permission {
	if in == nil {
		return nil
	}
	out := new(Permission)
	in.DeepCopyInto(out)
	return out
}

func (in *Permission) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *PermissionFeatures) DeepCopyInto(out *PermissionFeatures) {
	*out = *in
}

func (in *PermissionFeatures) DeepCopy() *PermissionFeatures {
	if in == nil {
		return nil
	}
	out := new(PermissionFeatures)
	in.DeepCopyInto(out)
	return out
}

func (in *PermissionList) DeepCopyInto(out *PermissionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Permission, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *PermissionList) DeepCopy() *PermissionList {
	if in == nil {
		return nil
	}
	out := new(PermissionList)
	in.DeepCopyInto(out)
	return out
}

func (in *PermissionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *PermissionSpec) DeepCopyInto(out *PermissionSpec) {
	*out = *in
	if in.Menu != nil {
		in, out := &in.Menu, &out.Menu
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.API != nil {
		in, out := &in.API, &out.API
		*out = make(map[string][]string, len(*in))
		for key, val := range *in {
			if val == nil {
				(*out)[key] = nil
				continue
			}
			outVal := make([]string, len(val))
			copy(outVal, val)
			(*out)[key] = outVal
		}
	}
	out.Features = in.Features
	if in.DomainWhiteList != nil {
		in, out := &in.DomainWhiteList, &out.DomainWhiteList
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.RBACRules != nil {
		in, out := &in.RBACRules, &out.RBACRules
		*out = make([]rbacv1.PolicyRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *PermissionSpec) DeepCopy() *PermissionSpec {
	if in == nil {
		return nil
	}
	out := new(PermissionSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *FilingConfig) DeepCopyInto(out *FilingConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
}

func (in *FilingConfig) DeepCopy() *FilingConfig {
	if in == nil {
		return nil
	}
	out := new(FilingConfig)
	in.DeepCopyInto(out)
	return out
}

func (in *FilingConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *FilingConfigList) DeepCopyInto(out *FilingConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]FilingConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *FilingConfigList) DeepCopy() *FilingConfigList {
	if in == nil {
		return nil
	}
	out := new(FilingConfigList)
	in.DeepCopyInto(out)
	return out
}

func (in *FilingConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *FilingConfigSpec) DeepCopyInto(out *FilingConfigSpec) {
	*out = *in
}

func (in *FilingConfigSpec) DeepCopy() *FilingConfigSpec {
	if in == nil {
		return nil
	}
	out := new(FilingConfigSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *DomainParseConfig) DeepCopyInto(out *DomainParseConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

func (in *DomainParseConfig) DeepCopy() *DomainParseConfig {
	if in == nil {
		return nil
	}
	out := new(DomainParseConfig)
	in.DeepCopyInto(out)
	return out
}

func (in *DomainParseConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *DomainParseConfigList) DeepCopyInto(out *DomainParseConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DomainParseConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *DomainParseConfigList) DeepCopy() *DomainParseConfigList {
	if in == nil {
		return nil
	}
	out := new(DomainParseConfigList)
	in.DeepCopyInto(out)
	return out
}

func (in *DomainParseConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *DomainParseConfigSpec) DeepCopyInto(out *DomainParseConfigSpec) {
	*out = *in
	if in.IPs != nil {
		in, out := &in.IPs, &out.IPs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

func (in *DomainParseConfigSpec) DeepCopy() *DomainParseConfigSpec {
	if in == nil {
		return nil
	}
	out := new(DomainParseConfigSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *ContactConfig) DeepCopyInto(out *ContactConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
}

func (in *ContactConfig) DeepCopy() *ContactConfig {
	if in == nil {
		return nil
	}
	out := new(ContactConfig)
	in.DeepCopyInto(out)
	return out
}

func (in *ContactConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *ContactConfigList) DeepCopyInto(out *ContactConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ContactConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *ContactConfigList) DeepCopy() *ContactConfigList {
	if in == nil {
		return nil
	}
	out := new(ContactConfigList)
	in.DeepCopyInto(out)
	return out
}

func (in *ContactConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *ContactConfigSpec) DeepCopyInto(out *ContactConfigSpec) {
	*out = *in
}

func (in *ContactConfigSpec) DeepCopy() *ContactConfigSpec {
	if in == nil {
		return nil
	}
	out := new(ContactConfigSpec)
	in.DeepCopyInto(out)
	return out
}
