/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"
	time "time"

	apismcpserverv1alpha1 "github.com/w7panel/w7panel/k8s/pkg/apis/mcpserver/v1alpha1"
	versioned "github.com/w7panel/w7panel/k8s/pkg/client/mcpserver/clientset/versioned"
	internalinterfaces "github.com/w7panel/w7panel/k8s/pkg/client/mcpserver/informers/externalversions/internalinterfaces"
	mcpserverv1alpha1 "github.com/w7panel/w7panel/k8s/pkg/client/mcpserver/listers/mcpserver/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// McpServerInformer provides access to a shared informer and lister for
// McpServers.
type McpServerInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() mcpserverv1alpha1.McpServerLister
}

type mcpServerInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewMcpServerInformer constructs a new informer for McpServer type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewMcpServerInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredMcpServerInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredMcpServerInformer constructs a new informer for McpServer type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredMcpServerInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		cache.ToListWatcherWithWatchListSemantics(&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.McpserverV1alpha1().McpServers(namespace).List(context.Background(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.McpserverV1alpha1().McpServers(namespace).Watch(context.Background(), options)
			},
			ListWithContextFunc: func(ctx context.Context, options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.McpserverV1alpha1().McpServers(namespace).List(ctx, options)
			},
			WatchFuncWithContext: func(ctx context.Context, options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.McpserverV1alpha1().McpServers(namespace).Watch(ctx, options)
			},
		}, client),
		&apismcpserverv1alpha1.McpServer{},
		resyncPeriod,
		indexers,
	)
}

func (f *mcpServerInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredMcpServerInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *mcpServerInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&apismcpserverv1alpha1.McpServer{}, f.defaultInformer)
}

func (f *mcpServerInformer) Lister() mcpserverv1alpha1.McpServerLister {
	return mcpserverv1alpha1.NewMcpServerLister(f.Informer().GetIndexer())
}
