/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	appgroupv1alpha1 "github.com/w7panel/w7panel/k8s/pkg/apis/appgroup/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// AppGroupLister helps list AppGroups.
// All objects returned here must be treated as read-only.
type AppGroupLister interface {
	// List lists all AppGroups in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*appgroupv1alpha1.AppGroup, err error)
	// AppGroups returns an object that can list and get AppGroups.
	AppGroups(namespace string) AppGroupNamespaceLister
	AppGroupListerExpansion
}

// appGroupLister implements the AppGroupLister interface.
type appGroupLister struct {
	listers.ResourceIndexer[*appgroupv1alpha1.AppGroup]
}

// NewAppGroupLister returns a new AppGroupLister.
func NewAppGroupLister(indexer cache.Indexer) AppGroupLister {
	return &appGroupLister{listers.New[*appgroupv1alpha1.AppGroup](indexer, appgroupv1alpha1.Resource("appgroup"))}
}

// AppGroups returns an object that can list and get AppGroups.
func (s *appGroupLister) AppGroups(namespace string) AppGroupNamespaceLister {
	return appGroupNamespaceLister{listers.NewNamespaced[*appgroupv1alpha1.AppGroup](s.ResourceIndexer, namespace)}
}

// AppGroupNamespaceLister helps list and get AppGroups.
// All objects returned here must be treated as read-only.
type AppGroupNamespaceLister interface {
	// List lists all AppGroups in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*appgroupv1alpha1.AppGroup, err error)
	// Get retrieves the AppGroup from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*appgroupv1alpha1.AppGroup, error)
	AppGroupNamespaceListerExpansion
}

// appGroupNamespaceLister implements the AppGroupNamespaceLister
// interface.
type appGroupNamespaceLister struct {
	listers.ResourceIndexer[*appgroupv1alpha1.AppGroup]
}
