/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	k3kiov1alpha1 "github.com/rancher/k3k/pkg/apis/k3k.io/v1alpha1"
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// CvmStatusApplyConfiguration represents a declarative configuration of the CvmStatus type for use
// with apply.
//
// 【微擎面板&集群云主机：云主机业务分离成独立应用】
// https://www.tapd.cn/tapd_fe/62789787/story/detail/1162789787001015242
type CvmStatusApplyConfiguration struct {
	Phase        *string                     `json:"phase,omitempty"`
	ClusterPhase *k3kiov1alpha1.ClusterPhase `json:"clusterPhase,omitempty"`
	// ReadyReplicas     int32              `json:"readyReplicas,omitempty"`
	EffectiveResource *CvmResourceApplyConfiguration `json:"effectiveResource,omitempty"`
	// UserResource + PurchasedResource
	Conditions []v1.ConditionApplyConfiguration `json:"conditions,omitempty"`
	IsExpired  *bool                            `json:"isExpired,omitempty"`
	// 是否过期
	IsRecycling *bool `json:"isRecycling,omitempty"`
}

// CvmStatusApplyConfiguration constructs a declarative configuration of the CvmStatus type for use with
// apply.
func CvmStatus() *CvmStatusApplyConfiguration {
	return &CvmStatusApplyConfiguration{}
}

// WithPhase sets the Phase field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Phase field is set to the value of the last call.
func (b *CvmStatusApplyConfiguration) WithPhase(value string) *CvmStatusApplyConfiguration {
	b.Phase = &value
	return b
}

// WithClusterPhase sets the ClusterPhase field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ClusterPhase field is set to the value of the last call.
func (b *CvmStatusApplyConfiguration) WithClusterPhase(value k3kiov1alpha1.ClusterPhase) *CvmStatusApplyConfiguration {
	b.ClusterPhase = &value
	return b
}

// WithEffectiveResource sets the EffectiveResource field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the EffectiveResource field is set to the value of the last call.
func (b *CvmStatusApplyConfiguration) WithEffectiveResource(value *CvmResourceApplyConfiguration) *CvmStatusApplyConfiguration {
	b.EffectiveResource = value
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *CvmStatusApplyConfiguration) WithConditions(values ...*v1.ConditionApplyConfiguration) *CvmStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}

// WithIsExpired sets the IsExpired field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IsExpired field is set to the value of the last call.
func (b *CvmStatusApplyConfiguration) WithIsExpired(value bool) *CvmStatusApplyConfiguration {
	b.IsExpired = &value
	return b
}

// WithIsRecycling sets the IsRecycling field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IsRecycling field is set to the value of the last call.
func (b *CvmStatusApplyConfiguration) WithIsRecycling(value bool) *CvmStatusApplyConfiguration {
	b.IsRecycling = &value
	return b
}
