/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	k3kiov1alpha1 "github.com/rancher/k3k/pkg/apis/k3k.io/v1alpha1"
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// CvmStatusApplyConfiguration represents a declarative configuration of the CvmStatus type for use
// with apply.
type CvmStatusApplyConfiguration struct {
	Phase             *string                        `json:"phase,omitempty"`
	ClusterPhase      *k3kiov1alpha1.ClusterPhase    `json:"clusterPhase,omitempty"`
	EffectiveResource *CvmResourceApplyConfiguration `json:"effectiveResource,omitempty"`
	// UserResource + PurchasedResource
	Conditions []v1.ConditionApplyConfiguration `json:"conditions,omitempty"`
	IsExpired  *bool                            `json:"isExpired,omitempty"`
	// 是否过期
	IsRecycling *bool `json:"isRecycling,omitempty"`
	// 是否回收中
	CanBaseBuy *bool `json:"canBaseBuy,omitempty"`
	// 是否可以购买基础套餐
	CanExpandBuy *bool `json:"canExpandBuy,omitempty"`
	// 是否可以扩容
	CanRenewBuy *bool `json:"canRenewBuy,omitempty"`
	// 是否可以续费
	CanDelete *bool `json:"canDelete,omitempty"`
	// 是否可以续费
	DiffMonth *string `json:"diffMonth,omitempty"`
	// 到期时间剩余月数
	Server0PodName       *string `json:"server0PodName,omitempty"`
	Server0ContainerName *string `json:"server0ContainerName,omitempty"`
	K3kStatufulSetName   *string `json:"k3kStatufulSetName,omitempty"`
	RescueJobName        *string `json:"rescueJobName,omitempty"`
	// 救援job名称
	RescuePhase *string `json:"rescuePhase,omitempty"`
}

// CvmStatusApplyConfiguration constructs a declarative configuration of the CvmStatus type for use with
// apply.
func CvmStatus() *CvmStatusApplyConfiguration {
	return &CvmStatusApplyConfiguration{}
}

// WithPhase sets the Phase field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Phase field is set to the value of the last call.
func (b *CvmStatusApplyConfiguration) WithPhase(value string) *CvmStatusApplyConfiguration {
	b.Phase = &value
	return b
}

// WithClusterPhase sets the ClusterPhase field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ClusterPhase field is set to the value of the last call.
func (b *CvmStatusApplyConfiguration) WithClusterPhase(value k3kiov1alpha1.ClusterPhase) *CvmStatusApplyConfiguration {
	b.ClusterPhase = &value
	return b
}

// WithEffectiveResource sets the EffectiveResource field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the EffectiveResource field is set to the value of the last call.
func (b *CvmStatusApplyConfiguration) WithEffectiveResource(value *CvmResourceApplyConfiguration) *CvmStatusApplyConfiguration {
	b.EffectiveResource = value
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *CvmStatusApplyConfiguration) WithConditions(values ...*v1.ConditionApplyConfiguration) *CvmStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}

// WithIsExpired sets the IsExpired field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IsExpired field is set to the value of the last call.
func (b *CvmStatusApplyConfiguration) WithIsExpired(value bool) *CvmStatusApplyConfiguration {
	b.IsExpired = &value
	return b
}

// WithIsRecycling sets the IsRecycling field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IsRecycling field is set to the value of the last call.
func (b *CvmStatusApplyConfiguration) WithIsRecycling(value bool) *CvmStatusApplyConfiguration {
	b.IsRecycling = &value
	return b
}

// WithCanBaseBuy sets the CanBaseBuy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CanBaseBuy field is set to the value of the last call.
func (b *CvmStatusApplyConfiguration) WithCanBaseBuy(value bool) *CvmStatusApplyConfiguration {
	b.CanBaseBuy = &value
	return b
}

// WithCanExpandBuy sets the CanExpandBuy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CanExpandBuy field is set to the value of the last call.
func (b *CvmStatusApplyConfiguration) WithCanExpandBuy(value bool) *CvmStatusApplyConfiguration {
	b.CanExpandBuy = &value
	return b
}

// WithCanRenewBuy sets the CanRenewBuy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CanRenewBuy field is set to the value of the last call.
func (b *CvmStatusApplyConfiguration) WithCanRenewBuy(value bool) *CvmStatusApplyConfiguration {
	b.CanRenewBuy = &value
	return b
}

// WithCanDelete sets the CanDelete field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CanDelete field is set to the value of the last call.
func (b *CvmStatusApplyConfiguration) WithCanDelete(value bool) *CvmStatusApplyConfiguration {
	b.CanDelete = &value
	return b
}

// WithDiffMonth sets the DiffMonth field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DiffMonth field is set to the value of the last call.
func (b *CvmStatusApplyConfiguration) WithDiffMonth(value string) *CvmStatusApplyConfiguration {
	b.DiffMonth = &value
	return b
}

// WithServer0PodName sets the Server0PodName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Server0PodName field is set to the value of the last call.
func (b *CvmStatusApplyConfiguration) WithServer0PodName(value string) *CvmStatusApplyConfiguration {
	b.Server0PodName = &value
	return b
}

// WithServer0ContainerName sets the Server0ContainerName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Server0ContainerName field is set to the value of the last call.
func (b *CvmStatusApplyConfiguration) WithServer0ContainerName(value string) *CvmStatusApplyConfiguration {
	b.Server0ContainerName = &value
	return b
}

// WithK3kStatufulSetName sets the K3kStatufulSetName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the K3kStatufulSetName field is set to the value of the last call.
func (b *CvmStatusApplyConfiguration) WithK3kStatufulSetName(value string) *CvmStatusApplyConfiguration {
	b.K3kStatufulSetName = &value
	return b
}

// WithRescueJobName sets the RescueJobName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RescueJobName field is set to the value of the last call.
func (b *CvmStatusApplyConfiguration) WithRescueJobName(value string) *CvmStatusApplyConfiguration {
	b.RescueJobName = &value
	return b
}

// WithRescuePhase sets the RescuePhase field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RescuePhase field is set to the value of the last call.
func (b *CvmStatusApplyConfiguration) WithRescuePhase(value string) *CvmStatusApplyConfiguration {
	b.RescuePhase = &value
	return b
}
