/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// CvmSpecApplyConfiguration represents a declarative configuration of the CvmSpec type for use
// with apply.
type CvmSpecApplyConfiguration struct {
	StorageClassName *string                        `json:"storageClassName,omitempty"`
	Workload         *WorkloadApplyConfiguration    `json:"workload,omitempty"`
	Resource         *CvmResourceApplyConfiguration `json:"resource,omitempty"`
	// 可使用资源
	BaseOrder    *CvmOrderApplyConfiguration    `json:"baseOrder,omitempty"`
	ExpandOrder  *CvmOrderApplyConfiguration    `json:"expandOrder,omitempty"`
	RenewOrder   *CvmOrderApplyConfiguration    `json:"renewOrder,omitempty"`
	BaseResource *CvmResourceApplyConfiguration `json:"baseResource,omitempty"`
}

// CvmSpecApplyConfiguration constructs a declarative configuration of the CvmSpec type for use with
// apply.
func CvmSpec() *CvmSpecApplyConfiguration {
	return &CvmSpecApplyConfiguration{}
}

// WithStorageClassName sets the StorageClassName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the StorageClassName field is set to the value of the last call.
func (b *CvmSpecApplyConfiguration) WithStorageClassName(value string) *CvmSpecApplyConfiguration {
	b.StorageClassName = &value
	return b
}

// WithWorkload sets the Workload field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Workload field is set to the value of the last call.
func (b *CvmSpecApplyConfiguration) WithWorkload(value *WorkloadApplyConfiguration) *CvmSpecApplyConfiguration {
	b.Workload = value
	return b
}

// WithResource sets the Resource field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Resource field is set to the value of the last call.
func (b *CvmSpecApplyConfiguration) WithResource(value *CvmResourceApplyConfiguration) *CvmSpecApplyConfiguration {
	b.Resource = value
	return b
}

// WithBaseOrder sets the BaseOrder field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BaseOrder field is set to the value of the last call.
func (b *CvmSpecApplyConfiguration) WithBaseOrder(value *CvmOrderApplyConfiguration) *CvmSpecApplyConfiguration {
	b.BaseOrder = value
	return b
}

// WithExpandOrder sets the ExpandOrder field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ExpandOrder field is set to the value of the last call.
func (b *CvmSpecApplyConfiguration) WithExpandOrder(value *CvmOrderApplyConfiguration) *CvmSpecApplyConfiguration {
	b.ExpandOrder = value
	return b
}

// WithRenewOrder sets the RenewOrder field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RenewOrder field is set to the value of the last call.
func (b *CvmSpecApplyConfiguration) WithRenewOrder(value *CvmOrderApplyConfiguration) *CvmSpecApplyConfiguration {
	b.RenewOrder = value
	return b
}

// WithBaseResource sets the BaseResource field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BaseResource field is set to the value of the last call.
func (b *CvmSpecApplyConfiguration) WithBaseResource(value *CvmResourceApplyConfiguration) *CvmSpecApplyConfiguration {
	b.BaseResource = value
	return b
}
