/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// CvmSpecApplyConfiguration represents a declarative configuration of the CvmSpec type for use
// with apply.
type CvmSpecApplyConfiguration struct {
	CPU       *int64 `json:"cpu,omitempty"`
	Memory    *int64 `json:"memory,omitempty"`
	Storage   *int64 `json:"storage,omitempty"`
	Bandwidth *int64 `json:"bandwidth,omitempty"`
}

// CvmSpecApplyConfiguration constructs a declarative configuration of the CvmSpec type for use with
// apply.
func CvmSpec() *CvmSpecApplyConfiguration {
	return &CvmSpecApplyConfiguration{}
}

// WithCPU sets the CPU field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CPU field is set to the value of the last call.
func (b *CvmSpecApplyConfiguration) WithCPU(value int64) *CvmSpecApplyConfiguration {
	b.CPU = &value
	return b
}

// WithMemory sets the Memory field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Memory field is set to the value of the last call.
func (b *CvmSpecApplyConfiguration) WithMemory(value int64) *CvmSpecApplyConfiguration {
	b.Memory = &value
	return b
}

// WithStorage sets the Storage field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Storage field is set to the value of the last call.
func (b *CvmSpecApplyConfiguration) WithStorage(value int64) *CvmSpecApplyConfiguration {
	b.Storage = &value
	return b
}

// WithBandwidth sets the Bandwidth field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Bandwidth field is set to the value of the last call.
func (b *CvmSpecApplyConfiguration) WithBandwidth(value int64) *CvmSpecApplyConfiguration {
	b.Bandwidth = &value
	return b
}
