/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// CvmSpecApplyConfiguration represents a declarative configuration of the CvmSpec type for use
// with apply.
type CvmSpecApplyConfiguration struct {
	StorageClassName *string                        `json:"storageClassName,omitempty"`
	Workload         *WorkloadApplyConfiguration    `json:"workload,omitempty"`
	UserResource     *CvmResourceApplyConfiguration `json:"userResource,omitempty"`
	// 强制指定资源，直接生效
	PurchasedResource *CvmResourceApplyConfiguration `json:"purchasedResource,omitempty"`
	// 累计已购买资源，待容量检测后生效
	PendingPurchasedResource *CvmResourceApplyConfiguration `json:"pendingPurchasedResource,omitempty"`
	// 购买待生效的资源
	CapacityCheckState *string `json:"capacityCheckState,omitempty"`
	// wait/no-resource/success
	BaseOrder *CvmOrderApplyConfiguration `json:"baseOrder,omitempty"`
	// 首次购买 基础订单
	ExpandOrder *CvmOrderApplyConfiguration `json:"expandOrder,omitempty"`
	// 扩容订单
	RenewOrder *CvmOrderApplyConfiguration `json:"renewOrder,omitempty"`
	// 续费订单 延长到期时间
	ExpireTime *string `json:"expireTime,omitempty"`
	// 到期时间
	RecycleTime *string `json:"recycleTime,omitempty"`
	// 回收时间RECYCLE
	Rescue *bool `json:"rescue,omitempty"`
}

// CvmSpecApplyConfiguration constructs a declarative configuration of the CvmSpec type for use with
// apply.
func CvmSpec() *CvmSpecApplyConfiguration {
	return &CvmSpecApplyConfiguration{}
}

// WithStorageClassName sets the StorageClassName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the StorageClassName field is set to the value of the last call.
func (b *CvmSpecApplyConfiguration) WithStorageClassName(value string) *CvmSpecApplyConfiguration {
	b.StorageClassName = &value
	return b
}

// WithWorkload sets the Workload field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Workload field is set to the value of the last call.
func (b *CvmSpecApplyConfiguration) WithWorkload(value *WorkloadApplyConfiguration) *CvmSpecApplyConfiguration {
	b.Workload = value
	return b
}

// WithUserResource sets the UserResource field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UserResource field is set to the value of the last call.
func (b *CvmSpecApplyConfiguration) WithUserResource(value *CvmResourceApplyConfiguration) *CvmSpecApplyConfiguration {
	b.UserResource = value
	return b
}

// WithPurchasedResource sets the PurchasedResource field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PurchasedResource field is set to the value of the last call.
func (b *CvmSpecApplyConfiguration) WithPurchasedResource(value *CvmResourceApplyConfiguration) *CvmSpecApplyConfiguration {
	b.PurchasedResource = value
	return b
}

// WithPendingPurchasedResource sets the PendingPurchasedResource field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PendingPurchasedResource field is set to the value of the last call.
func (b *CvmSpecApplyConfiguration) WithPendingPurchasedResource(value *CvmResourceApplyConfiguration) *CvmSpecApplyConfiguration {
	b.PendingPurchasedResource = value
	return b
}

// WithCapacityCheckState sets the CapacityCheckState field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CapacityCheckState field is set to the value of the last call.
func (b *CvmSpecApplyConfiguration) WithCapacityCheckState(value string) *CvmSpecApplyConfiguration {
	b.CapacityCheckState = &value
	return b
}

// WithBaseOrder sets the BaseOrder field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BaseOrder field is set to the value of the last call.
func (b *CvmSpecApplyConfiguration) WithBaseOrder(value *CvmOrderApplyConfiguration) *CvmSpecApplyConfiguration {
	b.BaseOrder = value
	return b
}

// WithExpandOrder sets the ExpandOrder field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ExpandOrder field is set to the value of the last call.
func (b *CvmSpecApplyConfiguration) WithExpandOrder(value *CvmOrderApplyConfiguration) *CvmSpecApplyConfiguration {
	b.ExpandOrder = value
	return b
}

// WithRenewOrder sets the RenewOrder field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RenewOrder field is set to the value of the last call.
func (b *CvmSpecApplyConfiguration) WithRenewOrder(value *CvmOrderApplyConfiguration) *CvmSpecApplyConfiguration {
	b.RenewOrder = value
	return b
}

// WithExpireTime sets the ExpireTime field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ExpireTime field is set to the value of the last call.
func (b *CvmSpecApplyConfiguration) WithExpireTime(value string) *CvmSpecApplyConfiguration {
	b.ExpireTime = &value
	return b
}

// WithRecycleTime sets the RecycleTime field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RecycleTime field is set to the value of the last call.
func (b *CvmSpecApplyConfiguration) WithRecycleTime(value string) *CvmSpecApplyConfiguration {
	b.RecycleTime = &value
	return b
}

// WithRescue sets the Rescue field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Rescue field is set to the value of the last call.
func (b *CvmSpecApplyConfiguration) WithRescue(value bool) *CvmSpecApplyConfiguration {
	b.Rescue = &value
	return b
}
