/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	appgroupv1alpha1 "github.com/w7panel/w7panel/k8s/pkg/apis/appgroup/v1alpha1"
	applyconfigurationappgroupv1alpha1 "github.com/w7panel/w7panel/k8s/pkg/client/appgroup/applyconfiguration/appgroup/v1alpha1"
	scheme "github.com/w7panel/w7panel/k8s/pkg/client/appgroup/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// AppGroupsGetter has a method to return a AppGroupInterface.
// A group's client should implement this interface.
type AppGroupsGetter interface {
	AppGroups(namespace string) AppGroupInterface
}

// AppGroupInterface has methods to work with AppGroup resources.
type AppGroupInterface interface {
	Create(ctx context.Context, appGroup *appgroupv1alpha1.AppGroup, opts v1.CreateOptions) (*appgroupv1alpha1.AppGroup, error)
	Update(ctx context.Context, appGroup *appgroupv1alpha1.AppGroup, opts v1.UpdateOptions) (*appgroupv1alpha1.AppGroup, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, appGroup *appgroupv1alpha1.AppGroup, opts v1.UpdateOptions) (*appgroupv1alpha1.AppGroup, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*appgroupv1alpha1.AppGroup, error)
	List(ctx context.Context, opts v1.ListOptions) (*appgroupv1alpha1.AppGroupList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *appgroupv1alpha1.AppGroup, err error)
	Apply(ctx context.Context, appGroup *applyconfigurationappgroupv1alpha1.AppGroupApplyConfiguration, opts v1.ApplyOptions) (result *appgroupv1alpha1.AppGroup, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, appGroup *applyconfigurationappgroupv1alpha1.AppGroupApplyConfiguration, opts v1.ApplyOptions) (result *appgroupv1alpha1.AppGroup, err error)
	AppGroupExpansion
}

// appGroups implements AppGroupInterface
type appGroups struct {
	*gentype.ClientWithListAndApply[*appgroupv1alpha1.AppGroup, *appgroupv1alpha1.AppGroupList, *applyconfigurationappgroupv1alpha1.AppGroupApplyConfiguration]
}

// newAppGroups returns a AppGroups
func newAppGroups(c *AppgroupV1alpha1Client, namespace string) *appGroups {
	return &appGroups{
		gentype.NewClientWithListAndApply[*appgroupv1alpha1.AppGroup, *appgroupv1alpha1.AppGroupList, *applyconfigurationappgroupv1alpha1.AppGroupApplyConfiguration](
			"appgroups",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *appgroupv1alpha1.AppGroup { return &appgroupv1alpha1.AppGroup{} },
			func() *appgroupv1alpha1.AppGroupList { return &appgroupv1alpha1.AppGroupList{} },
		),
	}
}
