/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	cvmv1alpha1 "github.com/w7panel/w7panel/k8s/pkg/apis/cvm/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// CvmConsoleOrderLister helps list CvmConsoleOrders.
// All objects returned here must be treated as read-only.
type CvmConsoleOrderLister interface {
	// List lists all CvmConsoleOrders in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*cvmv1alpha1.CvmConsoleOrder, err error)
	// CvmConsoleOrders returns an object that can list and get CvmConsoleOrders.
	CvmConsoleOrders(namespace string) CvmConsoleOrderNamespaceLister
	CvmConsoleOrderListerExpansion
}

// cvmConsoleOrderLister implements the CvmConsoleOrderLister interface.
type cvmConsoleOrderLister struct {
	listers.ResourceIndexer[*cvmv1alpha1.CvmConsoleOrder]
}

// NewCvmConsoleOrderLister returns a new CvmConsoleOrderLister.
func NewCvmConsoleOrderLister(indexer cache.Indexer) CvmConsoleOrderLister {
	return &cvmConsoleOrderLister{listers.New[*cvmv1alpha1.CvmConsoleOrder](indexer, cvmv1alpha1.Resource("cvmconsoleorder"))}
}

// CvmConsoleOrders returns an object that can list and get CvmConsoleOrders.
func (s *cvmConsoleOrderLister) CvmConsoleOrders(namespace string) CvmConsoleOrderNamespaceLister {
	return cvmConsoleOrderNamespaceLister{listers.NewNamespaced[*cvmv1alpha1.CvmConsoleOrder](s.ResourceIndexer, namespace)}
}

// CvmConsoleOrderNamespaceLister helps list and get CvmConsoleOrders.
// All objects returned here must be treated as read-only.
type CvmConsoleOrderNamespaceLister interface {
	// List lists all CvmConsoleOrders in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*cvmv1alpha1.CvmConsoleOrder, err error)
	// Get retrieves the CvmConsoleOrder from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*cvmv1alpha1.CvmConsoleOrder, error)
	CvmConsoleOrderNamespaceListerExpansion
}

// cvmConsoleOrderNamespaceLister implements the CvmConsoleOrderNamespaceLister
// interface.
type cvmConsoleOrderNamespaceLister struct {
	listers.ResourceIndexer[*cvmv1alpha1.CvmConsoleOrder]
}
