/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	cvmv1alpha1 "github.com/w7panel/w7panel/k8s/pkg/apis/cvm/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// CvmListLister helps list CvmLists.
// All objects returned here must be treated as read-only.
type CvmListLister interface {
	// List lists all CvmLists in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*cvmv1alpha1.CvmList, err error)
	// CvmLists returns an object that can list and get CvmLists.
	CvmLists(namespace string) CvmListNamespaceLister
	CvmListListerExpansion
}

// cvmListLister implements the CvmListLister interface.
type cvmListLister struct {
	listers.ResourceIndexer[*cvmv1alpha1.CvmList]
}

// NewCvmListLister returns a new CvmListLister.
func NewCvmListLister(indexer cache.Indexer) CvmListLister {
	return &cvmListLister{listers.New[*cvmv1alpha1.CvmList](indexer, cvmv1alpha1.Resource("cvmlist"))}
}

// CvmLists returns an object that can list and get CvmLists.
func (s *cvmListLister) CvmLists(namespace string) CvmListNamespaceLister {
	return cvmListNamespaceLister{listers.NewNamespaced[*cvmv1alpha1.CvmList](s.ResourceIndexer, namespace)}
}

// CvmListNamespaceLister helps list and get CvmLists.
// All objects returned here must be treated as read-only.
type CvmListNamespaceLister interface {
	// List lists all CvmLists in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*cvmv1alpha1.CvmList, err error)
	// Get retrieves the CvmList from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*cvmv1alpha1.CvmList, error)
	CvmListNamespaceListerExpansion
}

// cvmListNamespaceLister implements the CvmListNamespaceLister
// interface.
type cvmListNamespaceLister struct {
	listers.ResourceIndexer[*cvmv1alpha1.CvmList]
}
