apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: longhorn
  namespace: kube-system
  labels:
    {{- include "w7panel-longhorn.labels" . | nindent 4 }}
spec:
  chart: https://cdn.w7.cc/w7panel/charts/longhorn-1.11.1.tgz
  version: v1.11.1
  targetNamespace: longhorn-system
  createNamespace: true
  set:
    longhornUI.replicas: 0
    csi.attacherReplicaCount: 1
    csi.provisionerReplicaCount: 1
    csi.resizerReplicaCount: 1
    csi.snapshotterReplicaCount: 1
    defaultSettings.storageReservedPercentageForDefaultDisk: "0"
    defaultSettings.createDefaultDiskLabeledNodes: "true"
    defaultSettings.replicaSoftAntiAffinity: "true"
    defaultSettings.replicaDiskSoftAntiAffinity: "false"
    defaultSettings.replicaZoneSoftAntiAffinity: "true"
    defaultSettings.taintToleration: "node.kubernetes.io/unschedulable:NoSchedule; node.kubernetes.io/storage:NoSchedule"
    global.tolerations[0].key: node.kubernetes.io/unschedulable
    global.tolerations[0].operator: Exists
    global.tolerations[0].effect: NoSchedule
    global.tolerations[1].key: node.kubernetes.io/storage
    global.tolerations[1].operator: Exists
    global.tolerations[1].effect: NoSchedule

