
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: longhorn-nfs-installation
  namespace: kube-system
  labels:
    app: longhorn-nfs-installation
    {{- include "w7panel-longhorn.labels" . | nindent 4 }}
  annotations:
    command: &cmd OS=$(grep -E "^ID_LIKE=" /etc/os-release | cut -d '=' -f 2); if [[ -z "${OS}" ]]; then OS=$(grep -E "^ID=" /etc/os-release | cut -d '=' -f 2); fi; if [[ "${OS}" == *"debian"* ]]; then sudo apt-get update -q -y && sudo apt-get install -q -y nfs-common && sudo systemctl -q enable rpcbind && sudo systemctl restart rpcbind; elif [[ "${OS}" == *"suse"* ]]; then sudo zypper --gpg-auto-import-keys -q refresh && sudo zypper --gpg-auto-import-keys -q install -y nfs-client && sudo systemctl -q enable rpcbind && sudo systemctl restart rpcbind; else sudo yum makecache -q -y && sudo yum --setopt=tsflags=noscripts install -q -y nfs-utils && sudo systemctl -q enable rpcbind && sudo systemctl restart rpcbind; fi && if [ $? -eq 0 ]; then echo "nfs client install successfully"; else echo "nfs client install failed error code $?"; fi
spec:
  selector:
    matchLabels:
      app: longhorn-nfs-installation
  template:
    metadata:
      labels:
        app: longhorn-nfs-installation
    spec:
      hostNetwork: true
      hostPID: true
      initContainers:
      - name: nfs-installation
        command:
          - nsenter
          - --mount=/proc/1/ns/mnt
          - --
          - bash
          - -c
          - *cmd
        image: busybox:latest
        securityContext:
          privileged: true
      containers:
      - name: sleep
        image: rancher/mirrored-pause:3.6
  updateStrategy:
    type: RollingUpdate

