apiVersion: v2
appVersion: 1.16.0
deprecated: false
description: higress 限流
home: ""
icon: ""
kubeVersion: ""
name: w7panel-pluginratelimit
type: application
version: 0.1.0


annotations:
  w7.cc/title: "higress限流"
  w7.cc/description: "higress限流"
  title: "higress限流"
  w7.cc/deny-delete: "true"
  w7.cc/icon: "https://zpk.fan.b2.sz.w7.com/zpk/zip/icon/w7panel-pluginratelimit"
  w7.cc/zpk-url: "https://zpk.fan.b2.sz.w7.com/zpk/respo/info/w7panel-pluginratelimit"
  w7.cc/identifie: "w7panel-pluginratelimit"