/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"
	time "time"

	apismicroappsettingv1alpha1 "github.com/w7panel/w7panel/k8s/pkg/apis/microappsetting/v1alpha1"
	versioned "github.com/w7panel/w7panel/k8s/pkg/client/microappsetting/clientset/versioned"
	internalinterfaces "github.com/w7panel/w7panel/k8s/pkg/client/microappsetting/informers/externalversions/internalinterfaces"
	microappsettingv1alpha1 "github.com/w7panel/w7panel/k8s/pkg/client/microappsetting/listers/microappsetting/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// MicroAppSettingInformer provides access to a shared informer and lister for
// MicroAppSettings.
type MicroAppSettingInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() microappsettingv1alpha1.MicroAppSettingLister
}

type microAppSettingInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewMicroAppSettingInformer constructs a new informer for MicroAppSetting type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewMicroAppSettingInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredMicroAppSettingInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredMicroAppSettingInformer constructs a new informer for MicroAppSetting type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredMicroAppSettingInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		cache.ToListWatcherWithWatchListSemantics(&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.W7panelV1alpha1().MicroAppSettings(namespace).List(context.Background(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.W7panelV1alpha1().MicroAppSettings(namespace).Watch(context.Background(), options)
			},
			ListWithContextFunc: func(ctx context.Context, options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.W7panelV1alpha1().MicroAppSettings(namespace).List(ctx, options)
			},
			WatchFuncWithContext: func(ctx context.Context, options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.W7panelV1alpha1().MicroAppSettings(namespace).Watch(ctx, options)
			},
		}, client),
		&apismicroappsettingv1alpha1.MicroAppSetting{},
		resyncPeriod,
		indexers,
	)
}

func (f *microAppSettingInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredMicroAppSettingInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *microAppSettingInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&apismicroappsettingv1alpha1.MicroAppSetting{}, f.defaultInformer)
}

func (f *microAppSettingInformer) Lister() microappsettingv1alpha1.MicroAppSettingLister {
	return microappsettingv1alpha1.NewMicroAppSettingLister(f.Informer().GetIndexer())
}
