/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// GpuClasssSpecApplyConfiguration represents a declarative configuration of the GpuClasssSpec type for use
// with apply.
//
// GpuClasssSpec defines the desired state of GpuClasss
type GpuClasssSpecApplyConfiguration struct {
	// INSERT ADDITIONAL SPEC FIELDS -- desired state of cluster
	GpuOperatorMode *string           `json:"gpuOperatorMode,omitempty"`
	VgpuMode        *string           `json:"vgpuMode,omitempty"`
	AppName         *string           `json:"appName,omitempty"`
	Enabled         *bool             `json:"enabled,omitempty"`
	Labels          map[string]string `json:"labels,omitempty"`
}

// GpuClasssSpecApplyConfiguration constructs a declarative configuration of the GpuClasssSpec type for use with
// apply.
func GpuClasssSpec() *GpuClasssSpecApplyConfiguration {
	return &GpuClasssSpecApplyConfiguration{}
}

// WithGpuOperatorMode sets the GpuOperatorMode field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the GpuOperatorMode field is set to the value of the last call.
func (b *GpuClasssSpecApplyConfiguration) WithGpuOperatorMode(value string) *GpuClasssSpecApplyConfiguration {
	b.GpuOperatorMode = &value
	return b
}

// WithVgpuMode sets the VgpuMode field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the VgpuMode field is set to the value of the last call.
func (b *GpuClasssSpecApplyConfiguration) WithVgpuMode(value string) *GpuClasssSpecApplyConfiguration {
	b.VgpuMode = &value
	return b
}

// WithAppName sets the AppName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AppName field is set to the value of the last call.
func (b *GpuClasssSpecApplyConfiguration) WithAppName(value string) *GpuClasssSpecApplyConfiguration {
	b.AppName = &value
	return b
}

// WithEnabled sets the Enabled field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Enabled field is set to the value of the last call.
func (b *GpuClasssSpecApplyConfiguration) WithEnabled(value bool) *GpuClasssSpecApplyConfiguration {
	b.Enabled = &value
	return b
}

// WithLabels puts the entries into the Labels field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Labels field,
// overwriting an existing map entries in Labels field with the same key.
func (b *GpuClasssSpecApplyConfiguration) WithLabels(entries map[string]string) *GpuClasssSpecApplyConfiguration {
	if b.Labels == nil && len(entries) > 0 {
		b.Labels = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.Labels[k] = v
	}
	return b
}
