apiVersion: v2
name: w7panel-cloudnoauth
description: API proxy for in-cluster unauthenticated requests to api.w7.cc.
type: application
version: 0.1.0
appVersion: "0.1.0"



annotations:
  w7.cc/title: "cloud_app授权代理"
  w7.cc/description: "cloud_app授权代理"
  title: "cloud_app授权代理"
  w7.cc/deny-delete: "true"
  w7.cc/icon: "https://zpk.w7.cc/zpk/zip/icon/w7panel_cloudnoauth"
  w7.cc/zpk-url: "https://zpk.w7.cc/zpk/respo/info/w7panel_cloudnoauth"
  w7.cc/identifie: "w7panel-cloudnoauth"