replicaCount: 1

image:
  repository: zpk.w7.cc/public/w7panel-cloudnoauth
  pullPolicy: IfNotPresent
  tag: v1.0.12

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

rbac:
  create: true

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  port: 80
  targetPort: http
  annotations: {}

ingress:
  enabled: false
  className: higress
  annotations: {}
  host: api.w7.cc
  path: /
  pathType: Prefix
  tls:
    enabled: true
    secretName: w7panel-noauth-tls
  certManager:
    enabled: true
    issuer:
      create: false
      name: w7-letsencrypt-prod
      kind: ClusterIssuer
      group: cert-manager.io
      selfSigned: false
    certificate:
      create: true
      name: ""
      duration: 87600h
      renewBefore: 720h
      privateKey:
        algorithm: RSA
        size: 2048
  gatewayServiceFQDN: higress-gateway.higress-system.svc.cluster.local.

containerPort: 80
panelNamespace: ""

env:
  APP_ENV: release
  SERVER_PORT: "80"
  PANEL_CREDENTIAL_CACHE_SECONDS: "600"
  PANEL_CREDENTIAL_NEGATIVE_CACHE_SECONDS: "60"
  API_PROXY_SCHEME: https
  API_PROXY_ALLOWED_HOST: api.w7.cc

extraEnv: []

dnsPolicy: None
dnsConfig:
  nameservers:
    - 114.114.114.114
    - 223.5.5.5
  options:
    - name: ndots
      value: "1"

resources: {}

livenessProbe:
  httpGet:
    path: /api/live
    port: http
  initialDelaySeconds: 10
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /api/live
    port: http
  initialDelaySeconds: 5
  periodSeconds: 10

nodeSelector: {}
tolerations: []
affinity: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80

privateDNS:
  enabled: true
  name: api-w7-cc
  domain: api.w7.cc
  targetFQDN: ""
  records: []
