//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApiClient) DeepCopyInto(out *ApiClient) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
<<<<<<< HEAD
	in.Status.DeepCopyInto(&out.Status)
=======
>>>>>>> dev-v1
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApiClient.
func (in *ApiClient) DeepCopy() *ApiClient {
	if in == nil {
		return nil
	}
	out := new(ApiClient)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ApiClient) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApiClientList) DeepCopyInto(out *ApiClientList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ApiClient, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApiClientList.
func (in *ApiClientList) DeepCopy() *ApiClientList {
	if in == nil {
		return nil
	}
	out := new(ApiClientList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ApiClientList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApiClientSpec) DeepCopyInto(out *ApiClientSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApiClientSpec.
func (in *ApiClientSpec) DeepCopy() *ApiClientSpec {
	if in == nil {
		return nil
	}
	out := new(ApiClientSpec)
	in.DeepCopyInto(out)
	return out
}
<<<<<<< HEAD

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApiClientStatus) DeepCopyInto(out *ApiClientStatus) {
	*out = *in
	if in.LastAccessedAt != nil {
		in, out := &in.LastAccessedAt, &out.LastAccessedAt
		*out = (*in).DeepCopy()
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApiClientStatus.
func (in *ApiClientStatus) DeepCopy() *ApiClientStatus {
	if in == nil {
		return nil
	}
	out := new(ApiClientStatus)
	in.DeepCopyInto(out)
	return out
}
=======
>>>>>>> dev-v1
