{{- if .Values.ciliumMetrics.enabled }}
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMPodScrape
metadata:
  name: {{ include "k8s-offline-metrics.fullname" . }}-cilium
  labels:
    {{- include "k8s-offline-metrics.labels" . | nindent 4 }}
spec:
  namespaceSelector:
    matchNames:
      - kube-system
  podMetricsEndpoints:
    - port: prometheus
      metricRelabelConfigs:
        - action: keep
          source_labels:
            - __name__
          regex: cilium_(drop_(count|bytes)_total|endpoint|unreachable_(nodes|health_endpoints)|bpf_map_pressure|version)
      relabelConfigs:
        - action: replace
          sourceLabels:
            - __meta_kubernetes_pod_node_name
          targetLabel: node
  selector:
    matchLabels:
      k8s-app: cilium
{{- end }}
