{{- if .Values.hubbleMetrics.enabled }}
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMPodScrape
metadata:
  name: {{ include "k8s-offline-metrics.fullname" . }}-hubble
  labels:
    {{- include "k8s-offline-metrics.labels" . | nindent 4 }}
spec:
  namespaceSelector:
    matchNames:
      - kube-system
  podMetricsEndpoints:
    - port: hubble-metrics
      metricRelabelConfigs:
        - action: keep
          source_labels:
            - __name__
          regex: hubble_.*
      relabelConfigs:
        - action: replace
          sourceLabels:
            - __meta_kubernetes_pod_node_name
          targetLabel: node
  selector:
    matchLabels:
      k8s-app: cilium
{{- end }}
