{{- if .Values.nodeexporter.pod.enabled}}
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMPodScrape
metadata:
   name: {{ include "k8s-offline-metrics.fullname" . }}-node-exporter
   labels:
         {{- include "k8s-offline-metrics.labels" . | nindent 4 }}
spec:
    namespaceSelector:
        matchNames:
            - default
    podMetricsEndpoints:
        -
            bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
            port: metrics
            relabelConfigs:
                -
                    action: replace
                    sourceLabels:
                        - __meta_kubernetes_pod_node_name
                    targetLabel: instance
            scheme: https
            tlsConfig:
                caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
                insecureSkipVerify: true
    selector:
        matchLabels:
            app.kubernetes.io/instance: w7panel-metrics
            app.kubernetes.io/name: prometheus-node-exporter
            app.kubernetes.io/part-of: prometheus-node-exporter

{{- end }}


