{{- if .Values.alerting.enabled }}
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAlertmanager
metadata:
  name: {{ include "k8s-offline-metrics.fullname" . }}-alertmanager
  labels:
    {{- include "k8s-offline-metrics.labels" . | nindent 4 }}
    app.kubernetes.io/component: alertmanager
spec:
  configRawYaml: |
    global:
      resolve_timeout: 5m
    route:
      receiver: dingding
      group_by: [alertname, node, mountpoint]
      group_wait: {{ .Values.alerting.groupWait }}
      group_interval: {{ .Values.alerting.groupInterval }}
      repeat_interval: {{ .Values.alerting.repeatInterval }}
    receivers:
      - name: dingding
        webhook_configs:
          - url: {{ .Values.alerting.webhookURL | quote }}
            send_resolved: true
{{- end }}
