/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// BuildImageSpecApplyConfiguration represents a declarative configuration of the BuildImageSpec type for use
// with apply.
type BuildImageSpecApplyConfiguration struct {
	TaskID    *string `json:"taskId,omitempty"`
	Namespace *string `json:"namespace,omitempty"`
	Source    *struct {
		DownloadURL    string
		DockerfilePath string
	} `json:"source,omitempty"`
	TargetImage *struct {
		Address string
		Auth    struct {
			Username string
			Password string
		}
	} `json:"targetImage,omitempty"`
	NotifyURL *string `json:"notifyUrl,omitempty"`
}

// BuildImageSpecApplyConfiguration constructs a declarative configuration of the BuildImageSpec type for use with
// apply.
func BuildImageSpec() *BuildImageSpecApplyConfiguration {
	return &BuildImageSpecApplyConfiguration{}
}

// WithTaskID sets the TaskID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TaskID field is set to the value of the last call.
func (b *BuildImageSpecApplyConfiguration) WithTaskID(value string) *BuildImageSpecApplyConfiguration {
	b.TaskID = &value
	return b
}

// WithNamespace sets the Namespace field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Namespace field is set to the value of the last call.
func (b *BuildImageSpecApplyConfiguration) WithNamespace(value string) *BuildImageSpecApplyConfiguration {
	b.Namespace = &value
	return b
}

// WithSource sets the Source field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Source field is set to the value of the last call.
func (b *BuildImageSpecApplyConfiguration) WithSource(value struct {
	DownloadURL    string
	DockerfilePath string
}) *BuildImageSpecApplyConfiguration {
	b.Source = &value
	return b
}

// WithTargetImage sets the TargetImage field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TargetImage field is set to the value of the last call.
func (b *BuildImageSpecApplyConfiguration) WithTargetImage(value struct {
	Address string
	Auth    struct {
		Username string
		Password string
	}
}) *BuildImageSpecApplyConfiguration {
	b.TargetImage = &value
	return b
}

// WithNotifyURL sets the NotifyURL field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NotifyURL field is set to the value of the last call.
func (b *BuildImageSpecApplyConfiguration) WithNotifyURL(value string) *BuildImageSpecApplyConfiguration {
	b.NotifyURL = &value
	return b
}
