/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// BuildImageStatusApplyConfiguration represents a declarative configuration of the BuildImageStatus type for use
// with apply.
type BuildImageStatusApplyConfiguration struct {
	Status     *string                          `json:"status,omitempty"`
	Reason     *string                          `json:"reason,omitempty"`
	Contitions []v1.ConditionApplyConfiguration `json:"conditions,omitempty"`
	JobName    *string                          `json:"jobName,omitempty"`
}

// BuildImageStatusApplyConfiguration constructs a declarative configuration of the BuildImageStatus type for use with
// apply.
func BuildImageStatus() *BuildImageStatusApplyConfiguration {
	return &BuildImageStatusApplyConfiguration{}
}

// WithStatus sets the Status field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Status field is set to the value of the last call.
func (b *BuildImageStatusApplyConfiguration) WithStatus(value string) *BuildImageStatusApplyConfiguration {
	b.Status = &value
	return b
}

// WithReason sets the Reason field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Reason field is set to the value of the last call.
func (b *BuildImageStatusApplyConfiguration) WithReason(value string) *BuildImageStatusApplyConfiguration {
	b.Reason = &value
	return b
}

// WithContitions adds the given value to the Contitions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Contitions field.
func (b *BuildImageStatusApplyConfiguration) WithContitions(values ...*v1.ConditionApplyConfiguration) *BuildImageStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithContitions")
		}
		b.Contitions = append(b.Contitions, *values[i])
	}
	return b
}

// WithJobName sets the JobName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the JobName field is set to the value of the last call.
func (b *BuildImageStatusApplyConfiguration) WithJobName(value string) *BuildImageStatusApplyConfiguration {
	b.JobName = &value
	return b
}
