//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func (in *PrivateDNS) DeepCopyInto(out *PrivateDNS) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *PrivateDNS) DeepCopy() *PrivateDNS {
	if in == nil {
		return nil
	}
	out := new(PrivateDNS)
	in.DeepCopyInto(out)
	return out
}

func (in *PrivateDNS) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *PrivateDNSList) DeepCopyInto(out *PrivateDNSList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PrivateDNS, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *PrivateDNSList) DeepCopy() *PrivateDNSList {
	if in == nil {
		return nil
	}
	out := new(PrivateDNSList)
	in.DeepCopyInto(out)
	return out
}

func (in *PrivateDNSList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *PrivateDNSRecord) DeepCopyInto(out *PrivateDNSRecord) {
	*out = *in
}

func (in *PrivateDNSRecord) DeepCopy() *PrivateDNSRecord {
	if in == nil {
		return nil
	}
	out := new(PrivateDNSRecord)
	in.DeepCopyInto(out)
	return out
}

func (in *PrivateDNSSpec) DeepCopyInto(out *PrivateDNSSpec) {
	*out = *in
	if in.Records != nil {
		in, out := &in.Records, &out.Records
		*out = make([]PrivateDNSRecord, len(*in))
		copy(*out, *in)
	}
}

func (in *PrivateDNSSpec) DeepCopy() *PrivateDNSSpec {
	if in == nil {
		return nil
	}
	out := new(PrivateDNSSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *PrivateDNSStatus) DeepCopyInto(out *PrivateDNSStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *PrivateDNSStatus) DeepCopy() *PrivateDNSStatus {
	if in == nil {
		return nil
	}
	out := new(PrivateDNSStatus)
	in.DeepCopyInto(out)
	return out
}
