/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// AppGroupItemStatusApplyConfiguration represents a declarative configuration of the AppGroupItemStatus type for use
// with apply.
//
// ApplicationItemStatus 用于记录单个应用的部署状态信息
type AppGroupItemStatusApplyConfiguration struct {
	Kind *string `json:"kind,omitempty"`
	// "helm" or "deployment" or "statefulset" or "daemonset" or "job"
	ApiVersion     *string `json:"apiVersion,omitempty"`
	Name           *string `json:"name,omitempty"`
	Title          *string `json:"title,omitempty"`
	Ready          *bool   `json:"ready,omitempty"`
	IsHelmWorkLoad *bool   `json:"isHelmWorkLoad,omitempty"`
	// 是否为helm应用
	CreationTimestamp *v1.Time `json:"creationTimestamp,omitempty"`
	DeployStatus      *string  `json:"deployStatus,omitempty"`
	IsZeroReplicas    *bool    `json:"isZeroReplicas,omitempty"`
	// 是否暂停部署 只有一个应用并且replicas为0
	DenyDelete *bool `json:"denyDelete,omitempty"`
}

// AppGroupItemStatusApplyConfiguration constructs a declarative configuration of the AppGroupItemStatus type for use with
// apply.
func AppGroupItemStatus() *AppGroupItemStatusApplyConfiguration {
	return &AppGroupItemStatusApplyConfiguration{}
}

// WithKind sets the Kind field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Kind field is set to the value of the last call.
func (b *AppGroupItemStatusApplyConfiguration) WithKind(value string) *AppGroupItemStatusApplyConfiguration {
	b.Kind = &value
	return b
}

// WithApiVersion sets the ApiVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ApiVersion field is set to the value of the last call.
func (b *AppGroupItemStatusApplyConfiguration) WithApiVersion(value string) *AppGroupItemStatusApplyConfiguration {
	b.ApiVersion = &value
	return b
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *AppGroupItemStatusApplyConfiguration) WithName(value string) *AppGroupItemStatusApplyConfiguration {
	b.Name = &value
	return b
}

// WithTitle sets the Title field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Title field is set to the value of the last call.
func (b *AppGroupItemStatusApplyConfiguration) WithTitle(value string) *AppGroupItemStatusApplyConfiguration {
	b.Title = &value
	return b
}

// WithReady sets the Ready field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Ready field is set to the value of the last call.
func (b *AppGroupItemStatusApplyConfiguration) WithReady(value bool) *AppGroupItemStatusApplyConfiguration {
	b.Ready = &value
	return b
}

// WithIsHelmWorkLoad sets the IsHelmWorkLoad field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IsHelmWorkLoad field is set to the value of the last call.
func (b *AppGroupItemStatusApplyConfiguration) WithIsHelmWorkLoad(value bool) *AppGroupItemStatusApplyConfiguration {
	b.IsHelmWorkLoad = &value
	return b
}

// WithCreationTimestamp sets the CreationTimestamp field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CreationTimestamp field is set to the value of the last call.
func (b *AppGroupItemStatusApplyConfiguration) WithCreationTimestamp(value v1.Time) *AppGroupItemStatusApplyConfiguration {
	b.CreationTimestamp = &value
	return b
}

// WithDeployStatus sets the DeployStatus field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DeployStatus field is set to the value of the last call.
func (b *AppGroupItemStatusApplyConfiguration) WithDeployStatus(value string) *AppGroupItemStatusApplyConfiguration {
	b.DeployStatus = &value
	return b
}

// WithIsZeroReplicas sets the IsZeroReplicas field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IsZeroReplicas field is set to the value of the last call.
func (b *AppGroupItemStatusApplyConfiguration) WithIsZeroReplicas(value bool) *AppGroupItemStatusApplyConfiguration {
	b.IsZeroReplicas = &value
	return b
}

// WithDenyDelete sets the DenyDelete field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DenyDelete field is set to the value of the last call.
func (b *AppGroupItemStatusApplyConfiguration) WithDenyDelete(value bool) *AppGroupItemStatusApplyConfiguration {
	b.DenyDelete = &value
	return b
}
