// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// AppGroupDependencyApplyConfiguration represents a declarative configuration
// of the AppGroupDependency type for use with apply.
type AppGroupDependencyApplyConfiguration struct {
	Namespace       *string `json:"namespace,omitempty"`
	Name            *string `json:"name,omitempty"`
	Identifie       *string `json:"identifie,omitempty"`
	ApplicationType *string `json:"applicationType,omitempty"`
}

func AppGroupDependency() *AppGroupDependencyApplyConfiguration {
	return &AppGroupDependencyApplyConfiguration{}
}

func (b *AppGroupDependencyApplyConfiguration) WithNamespace(value string) *AppGroupDependencyApplyConfiguration {
	b.Namespace = &value
	return b
}

func (b *AppGroupDependencyApplyConfiguration) WithName(value string) *AppGroupDependencyApplyConfiguration {
	b.Name = &value
	return b
}

func (b *AppGroupDependencyApplyConfiguration) WithIdentifie(value string) *AppGroupDependencyApplyConfiguration {
	b.Identifie = &value
	return b
}

func (b *AppGroupDependencyApplyConfiguration) WithApplicationType(value string) *AppGroupDependencyApplyConfiguration {
	b.ApplicationType = &value
	return b
}
