/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// AppGroupSpecApplyConfiguration represents a declarative configuration of the AppGroupSpec type for use
// with apply.
type AppGroupSpecApplyConfiguration struct {
	Identifie *string `json:"identifie,omitempty"`
	// 应用标识
	Type *string `json:"type,omitempty"`
	// "helm" or "zpk" or "custom"
	Version *string `json:"version,omitempty"`
	// 版本号
	UpgradingVersion *string `json:"upgradingVersion,omitempty"`
	// 更新中的版本号
	Title *string `json:"title,omitempty"`
	// 应用标题
	Logo *string `json:"logo,omitempty"`
	// logo地址
	Description *string `json:"description,omitempty"`
	// 应用描述
	Suffix *string `json:"suffix,omitempty"`
	// Domains       []string   `json:"domains"`       //域名列表
	// DefaultDomain string     `json:"defaultDomain"` //默认域名
	ZpkUrl *string `json:"zpkUrl,omitempty"`
	// 制品库地址
	HelmConfig       *HelmConfigApplyConfiguration       `json:"helmConfig,omitempty"`
	AppCredentials   *AppCredentialsApplyConfiguration   `json:"appCredentials,omitempty"`
	ExternalServices []ExternalServiceApplyConfiguration `json:"externalServices,omitempty"`
	// Annotations   map[string]string `json:"annotations"`   //annotations
	IsHelm *bool `json:"isHelm,omitempty"`
}

// AppGroupSpecApplyConfiguration constructs a declarative configuration of the AppGroupSpec type for use with
// apply.
func AppGroupSpec() *AppGroupSpecApplyConfiguration {
	return &AppGroupSpecApplyConfiguration{}
}

// WithIdentifie sets the Identifie field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Identifie field is set to the value of the last call.
func (b *AppGroupSpecApplyConfiguration) WithIdentifie(value string) *AppGroupSpecApplyConfiguration {
	b.Identifie = &value
	return b
}

// WithType sets the Type field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Type field is set to the value of the last call.
func (b *AppGroupSpecApplyConfiguration) WithType(value string) *AppGroupSpecApplyConfiguration {
	b.Type = &value
	return b
}

// WithVersion sets the Version field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Version field is set to the value of the last call.
func (b *AppGroupSpecApplyConfiguration) WithVersion(value string) *AppGroupSpecApplyConfiguration {
	b.Version = &value
	return b
}

// WithUpgradingVersion sets the UpgradingVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UpgradingVersion field is set to the value of the last call.
func (b *AppGroupSpecApplyConfiguration) WithUpgradingVersion(value string) *AppGroupSpecApplyConfiguration {
	b.UpgradingVersion = &value
	return b
}

// WithTitle sets the Title field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Title field is set to the value of the last call.
func (b *AppGroupSpecApplyConfiguration) WithTitle(value string) *AppGroupSpecApplyConfiguration {
	b.Title = &value
	return b
}

// WithLogo sets the Logo field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Logo field is set to the value of the last call.
func (b *AppGroupSpecApplyConfiguration) WithLogo(value string) *AppGroupSpecApplyConfiguration {
	b.Logo = &value
	return b
}

// WithDescription sets the Description field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Description field is set to the value of the last call.
func (b *AppGroupSpecApplyConfiguration) WithDescription(value string) *AppGroupSpecApplyConfiguration {
	b.Description = &value
	return b
}

// WithSuffix sets the Suffix field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Suffix field is set to the value of the last call.
func (b *AppGroupSpecApplyConfiguration) WithSuffix(value string) *AppGroupSpecApplyConfiguration {
	b.Suffix = &value
	return b
}

// WithZpkUrl sets the ZpkUrl field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ZpkUrl field is set to the value of the last call.
func (b *AppGroupSpecApplyConfiguration) WithZpkUrl(value string) *AppGroupSpecApplyConfiguration {
	b.ZpkUrl = &value
	return b
}

// WithHelmConfig sets the HelmConfig field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the HelmConfig field is set to the value of the last call.
func (b *AppGroupSpecApplyConfiguration) WithHelmConfig(value *HelmConfigApplyConfiguration) *AppGroupSpecApplyConfiguration {
	b.HelmConfig = value
	return b
}

// WithAppCredentials sets the AppCredentials field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AppCredentials field is set to the value of the last call.
func (b *AppGroupSpecApplyConfiguration) WithAppCredentials(value *AppCredentialsApplyConfiguration) *AppGroupSpecApplyConfiguration {
	b.AppCredentials = value
	return b
}

// WithExternalServices adds the given value to the ExternalServices field in the declarative configuration
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ExternalServices field.
func (b *AppGroupSpecApplyConfiguration) WithExternalServices(values ...*ExternalServiceApplyConfiguration) *AppGroupSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithExternalServices")
		}
		b.ExternalServices = append(b.ExternalServices, *values[i])
	}
	return b
}

// WithIsHelm sets the IsHelm field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IsHelm field is set to the value of the last call.
func (b *AppGroupSpecApplyConfiguration) WithIsHelm(value bool) *AppGroupSpecApplyConfiguration {
	b.IsHelm = &value
	return b
}
