/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// DeployItemApplyConfiguration represents a declarative configuration of the DeployItem type for use
// with apply.
type DeployItemApplyConfiguration struct {
	Identifie *string `json:"identifie,omitempty"`
	// 应用标识
	Title *string `json:"title,omitempty"`
	// 应用标题
	ResourceList []ResourceInfoApplyConfiguration `json:"resourcesList,omitempty"`
	// 资源列表
	DeployStatus *string `json:"deployStatus,omitempty"`
}

// DeployItemApplyConfiguration constructs a declarative configuration of the DeployItem type for use with
// apply.
func DeployItem() *DeployItemApplyConfiguration {
	return &DeployItemApplyConfiguration{}
}

// WithIdentifie sets the Identifie field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Identifie field is set to the value of the last call.
func (b *DeployItemApplyConfiguration) WithIdentifie(value string) *DeployItemApplyConfiguration {
	b.Identifie = &value
	return b
}

// WithTitle sets the Title field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Title field is set to the value of the last call.
func (b *DeployItemApplyConfiguration) WithTitle(value string) *DeployItemApplyConfiguration {
	b.Title = &value
	return b
}

// WithResourceList adds the given value to the ResourceList field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ResourceList field.
func (b *DeployItemApplyConfiguration) WithResourceList(values ...*ResourceInfoApplyConfiguration) *DeployItemApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithResourceList")
		}
		b.ResourceList = append(b.ResourceList, *values[i])
	}
	return b
}

// WithDeployStatus sets the DeployStatus field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DeployStatus field is set to the value of the last call.
func (b *DeployItemApplyConfiguration) WithDeployStatus(value string) *DeployItemApplyConfiguration {
	b.DeployStatus = &value
	return b
}
