/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// ExternalServiceApplyConfiguration represents a declarative configuration of the ExternalService type for use
// with apply.
type ExternalServiceApplyConfiguration struct {
	Key      *string `json:"key,omitempty"`
	Title    *string `json:"title,omitempty"`
	URL      *string `json:"url,omitempty"`
	OpenMode *string `json:"openMode,omitempty"`
}

// ExternalServiceApplyConfiguration constructs a declarative configuration of the ExternalService type for use with
// apply.
func ExternalService() *ExternalServiceApplyConfiguration {
	return &ExternalServiceApplyConfiguration{}
}

// WithKey sets the Key field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Key field is set to the value of the last call.
func (b *ExternalServiceApplyConfiguration) WithKey(value string) *ExternalServiceApplyConfiguration {
	b.Key = &value
	return b
}

// WithTitle sets the Title field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Title field is set to the value of the last call.
func (b *ExternalServiceApplyConfiguration) WithTitle(value string) *ExternalServiceApplyConfiguration {
	b.Title = &value
	return b
}

// WithURL sets the URL field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the URL field is set to the value of the last call.
func (b *ExternalServiceApplyConfiguration) WithURL(value string) *ExternalServiceApplyConfiguration {
	b.URL = &value
	return b
}

// WithOpenMode sets the OpenMode field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the OpenMode field is set to the value of the last call.
func (b *ExternalServiceApplyConfiguration) WithOpenMode(value string) *ExternalServiceApplyConfiguration {
	b.OpenMode = &value
	return b
}
