/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// HelmConfigApplyConfiguration represents a declarative configuration of the HelmConfig type for use
// with apply.
type HelmConfigApplyConfiguration struct {
	ChartName *string `json:"chartName,omitempty"`
	// helm chart name
	Repository *string `json:"repository,omitempty"`
	// helm chart repository
	Version *string `json:"version,omitempty"`
}

// HelmConfigApplyConfiguration constructs a declarative configuration of the HelmConfig type for use with
// apply.
func HelmConfig() *HelmConfigApplyConfiguration {
	return &HelmConfigApplyConfiguration{}
}

// WithChartName sets the ChartName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ChartName field is set to the value of the last call.
func (b *HelmConfigApplyConfiguration) WithChartName(value string) *HelmConfigApplyConfiguration {
	b.ChartName = &value
	return b
}

// WithRepository sets the Repository field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Repository field is set to the value of the last call.
func (b *HelmConfigApplyConfiguration) WithRepository(value string) *HelmConfigApplyConfiguration {
	b.Repository = &value
	return b
}

// WithVersion sets the Version field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Version field is set to the value of the last call.
func (b *HelmConfigApplyConfiguration) WithVersion(value string) *HelmConfigApplyConfiguration {
	b.Version = &value
	return b
}
