/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// ContactConfigApplyConfiguration represents a declarative configuration of the ContactConfigSettings type for use
// with apply.
type ContactConfigApplyConfiguration struct {
	Type     *string `json:"type,omitempty"`
	Link     *string `json:"link,omitempty"`
	Text     *string `json:"text,omitempty"`
	Name     *string `json:"name,omitempty"`
	ShowName *bool   `json:"showName,omitempty"`
	SelIcon  *string `json:"selicon,omitempty"`
	Icon     *string `json:"icon,omitempty"`
	Qrcode   *string `json:"qrcode,omitempty"`
	Style    *string `json:"style,omitempty"`
	Index    *int32  `json:"index,omitempty"`
}

// ContactConfig constructs a declarative configuration of the ContactConfigSettings type for use with apply.
func ContactConfig() *ContactConfigApplyConfiguration {
	return &ContactConfigApplyConfiguration{}
}

// WithType sets the Type field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
func (b *ContactConfigApplyConfiguration) WithType(value string) *ContactConfigApplyConfiguration {
	b.Type = &value
	return b
}

// WithLink sets the Link field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
func (b *ContactConfigApplyConfiguration) WithLink(value string) *ContactConfigApplyConfiguration {
	b.Link = &value
	return b
}

// WithText sets the Text field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
func (b *ContactConfigApplyConfiguration) WithText(value string) *ContactConfigApplyConfiguration {
	b.Text = &value
	return b
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
func (b *ContactConfigApplyConfiguration) WithName(value string) *ContactConfigApplyConfiguration {
	b.Name = &value
	return b
}

// WithShowName sets the ShowName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
func (b *ContactConfigApplyConfiguration) WithShowName(value bool) *ContactConfigApplyConfiguration {
	b.ShowName = &value
	return b
}

// WithSelIcon sets the SelIcon field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
func (b *ContactConfigApplyConfiguration) WithSelIcon(value string) *ContactConfigApplyConfiguration {
	b.SelIcon = &value
	return b
}

// WithIcon sets the Icon field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
func (b *ContactConfigApplyConfiguration) WithIcon(value string) *ContactConfigApplyConfiguration {
	b.Icon = &value
	return b
}

// WithQrcode sets the Qrcode field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
func (b *ContactConfigApplyConfiguration) WithQrcode(value string) *ContactConfigApplyConfiguration {
	b.Qrcode = &value
	return b
}

// WithStyle sets the Style field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
func (b *ContactConfigApplyConfiguration) WithStyle(value string) *ContactConfigApplyConfiguration {
	b.Style = &value
	return b
}

// WithIndex sets the Index field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
func (b *ContactConfigApplyConfiguration) WithIndex(value int32) *ContactConfigApplyConfiguration {
	b.Index = &value
	return b
}
