/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// FilingSettingsApplyConfiguration represents a declarative configuration of the FilingSettings type for use
// with apply.
type FilingSettingsApplyConfiguration struct {
	ICP                              *string `json:"icp,omitempty"`
	PublicSecurityNetworkFiling      *string `json:"publicSecurityNetworkFiling,omitempty"`
	ElectronicBusinessLicense        *string `json:"electronicBusinessLicense,omitempty"`
	ValueAddedTelecomBusinessLicense *string `json:"valueAddedTelecomBusinessLicense,omitempty"`
}

// FilingSettingsApplyConfiguration constructs a declarative configuration of the FilingSettings type for use with
// apply.
func FilingSettings() *FilingSettingsApplyConfiguration {
	return &FilingSettingsApplyConfiguration{}
}

// WithICP sets the ICP field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ICP field is set to the value of the last call.
func (b *FilingSettingsApplyConfiguration) WithICP(value string) *FilingSettingsApplyConfiguration {
	b.ICP = &value
	return b
}

// WithPublicSecurityNetworkFiling sets the PublicSecurityNetworkFiling field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PublicSecurityNetworkFiling field is set to the value of the last call.
func (b *FilingSettingsApplyConfiguration) WithPublicSecurityNetworkFiling(value string) *FilingSettingsApplyConfiguration {
	b.PublicSecurityNetworkFiling = &value
	return b
}

// WithElectronicBusinessLicense sets the ElectronicBusinessLicense field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ElectronicBusinessLicense field is set to the value of the last call.
func (b *FilingSettingsApplyConfiguration) WithElectronicBusinessLicense(value string) *FilingSettingsApplyConfiguration {
	b.ElectronicBusinessLicense = &value
	return b
}

// WithValueAddedTelecomBusinessLicense sets the ValueAddedTelecomBusinessLicense field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ValueAddedTelecomBusinessLicense field is set to the value of the last call.
func (b *FilingSettingsApplyConfiguration) WithValueAddedTelecomBusinessLicense(value string) *FilingSettingsApplyConfiguration {
	b.ValueAddedTelecomBusinessLicense = &value
	return b
}
