/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// GeneralSettingsApplyConfiguration represents a declarative configuration of the GeneralSettings type for use
// with apply.
type GeneralSettingsApplyConfiguration struct {
	SiteName        *string                           `json:"siteName,omitempty"`
	SiteLogo        *ConfigMapRefApplyConfiguration   `json:"siteLogo,omitempty"`
	SiteDescription *string                           `json:"siteDescription,omitempty"`
	Filing          *FilingSettingsApplyConfiguration `json:"filing,omitempty"`
}

// GeneralSettingsApplyConfiguration constructs a declarative configuration of the GeneralSettings type for use with
// apply.
func GeneralSettings() *GeneralSettingsApplyConfiguration {
	return &GeneralSettingsApplyConfiguration{}
}

// WithSiteName sets the SiteName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SiteName field is set to the value of the last call.
func (b *GeneralSettingsApplyConfiguration) WithSiteName(value string) *GeneralSettingsApplyConfiguration {
	b.SiteName = &value
	return b
}

// WithSiteLogo sets the SiteLogo field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SiteLogo field is set to the value of the last call.
func (b *GeneralSettingsApplyConfiguration) WithSiteLogo(value *ConfigMapRefApplyConfiguration) *GeneralSettingsApplyConfiguration {
	b.SiteLogo = value
	return b
}

// WithSiteDescription sets the SiteDescription field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SiteDescription field is set to the value of the last call.
func (b *GeneralSettingsApplyConfiguration) WithSiteDescription(value string) *GeneralSettingsApplyConfiguration {
	b.SiteDescription = &value
	return b
}

// WithFiling sets the Filing field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Filing field is set to the value of the last call.
func (b *GeneralSettingsApplyConfiguration) WithFiling(value *FilingSettingsApplyConfiguration) *GeneralSettingsApplyConfiguration {
	b.Filing = value
	return b
}
