/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// MicroAppSettingSpecApplyConfiguration represents a declarative configuration of the MicroAppSettingSpec type for use
// with apply.
type MicroAppSettingSpecApplyConfiguration struct {
	Login   *LoginSettingsApplyConfiguration   `json:"login,omitempty"`
	General *GeneralSettingsApplyConfiguration `json:"general,omitempty"`
}

// MicroAppSettingSpecApplyConfiguration constructs a declarative configuration of the MicroAppSettingSpec type for use with
// apply.
func MicroAppSettingSpec() *MicroAppSettingSpecApplyConfiguration {
	return &MicroAppSettingSpecApplyConfiguration{}
}

// WithLogin sets the Login field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Login field is set to the value of the last call.
func (b *MicroAppSettingSpecApplyConfiguration) WithLogin(value *LoginSettingsApplyConfiguration) *MicroAppSettingSpecApplyConfiguration {
	b.Login = value
	return b
}

// WithGeneral sets the General field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the General field is set to the value of the last call.
func (b *MicroAppSettingSpecApplyConfiguration) WithGeneral(value *GeneralSettingsApplyConfiguration) *MicroAppSettingSpecApplyConfiguration {
	b.General = value
	return b
}
