//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArtifactAppGroupStatus) DeepCopyInto(out *ArtifactAppGroupStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArtifactAppGroupStatus.
func (in *ArtifactAppGroupStatus) DeepCopy() *ArtifactAppGroupStatus {
	if in == nil {
		return nil
	}
	out := new(ArtifactAppGroupStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArtifactInstallation) DeepCopyInto(out *ArtifactInstallation) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArtifactInstallation.
func (in *ArtifactInstallation) DeepCopy() *ArtifactInstallation {
	if in == nil {
		return nil
	}
	out := new(ArtifactInstallation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ArtifactInstallation) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArtifactInstallationList) DeepCopyInto(out *ArtifactInstallationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ArtifactInstallation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArtifactInstallationList.
func (in *ArtifactInstallationList) DeepCopy() *ArtifactInstallationList {
	if in == nil {
		return nil
	}
	out := new(ArtifactInstallationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ArtifactInstallationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArtifactInstallationSpec) DeepCopyInto(out *ArtifactInstallationSpec) {
	*out = *in
	out.ProfileRef = in.ProfileRef
	out.Artifact = in.Artifact
	out.Target = in.Target
	if in.DependsOn != nil {
		in, out := &in.DependsOn, &out.DependsOn
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.InstallOptions.DeepCopyInto(&out.InstallOptions)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArtifactInstallationSpec.
func (in *ArtifactInstallationSpec) DeepCopy() *ArtifactInstallationSpec {
	if in == nil {
		return nil
	}
	out := new(ArtifactInstallationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArtifactInstallationStatus) DeepCopyInto(out *ArtifactInstallationStatus) {
	*out = *in
	out.AppGroup = in.AppGroup
	if in.StartedAt != nil {
		in, out := &in.StartedAt, &out.StartedAt
		*out = (*in).DeepCopy()
	}
	if in.CompletedAt != nil {
		in, out := &in.CompletedAt, &out.CompletedAt
		*out = (*in).DeepCopy()
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArtifactInstallationStatus.
func (in *ArtifactInstallationStatus) DeepCopy() *ArtifactInstallationStatus {
	if in == nil {
		return nil
	}
	out := new(ArtifactInstallationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArtifactReference) DeepCopyInto(out *ArtifactReference) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArtifactReference.
func (in *ArtifactReference) DeepCopy() *ArtifactReference {
	if in == nil {
		return nil
	}
	out := new(ArtifactReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArtifactTarget) DeepCopyInto(out *ArtifactTarget) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArtifactTarget.
func (in *ArtifactTarget) DeepCopy() *ArtifactTarget {
	if in == nil {
		return nil
	}
	out := new(ArtifactTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BootstrapArtifact) DeepCopyInto(out *BootstrapArtifact) {
	*out = *in
	if in.DependsOn != nil {
		in, out := &in.DependsOn, &out.DependsOn
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.InstallOptions.DeepCopyInto(&out.InstallOptions)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BootstrapArtifact.
func (in *BootstrapArtifact) DeepCopy() *BootstrapArtifact {
	if in == nil {
		return nil
	}
	out := new(BootstrapArtifact)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BootstrapDefaults) DeepCopyInto(out *BootstrapDefaults) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BootstrapDefaults.
func (in *BootstrapDefaults) DeepCopy() *BootstrapDefaults {
	if in == nil {
		return nil
	}
	out := new(BootstrapDefaults)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BootstrapExpansionStatus) DeepCopyInto(out *BootstrapExpansionStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BootstrapExpansionStatus.
func (in *BootstrapExpansionStatus) DeepCopy() *BootstrapExpansionStatus {
	if in == nil {
		return nil
	}
	out := new(BootstrapExpansionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BootstrapInstallOptions) DeepCopyInto(out *BootstrapInstallOptions) {
	*out = *in
	if in.HelmValues != nil {
		in, out := &in.HelmValues, &out.HelmValues
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BootstrapInstallOptions.
func (in *BootstrapInstallOptions) DeepCopy() *BootstrapInstallOptions {
	if in == nil {
		return nil
	}
	out := new(BootstrapInstallOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BootstrapProfile) DeepCopyInto(out *BootstrapProfile) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BootstrapProfile.
func (in *BootstrapProfile) DeepCopy() *BootstrapProfile {
	if in == nil {
		return nil
	}
	out := new(BootstrapProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BootstrapProfile) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BootstrapProfileList) DeepCopyInto(out *BootstrapProfileList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BootstrapProfile, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BootstrapProfileList.
func (in *BootstrapProfileList) DeepCopy() *BootstrapProfileList {
	if in == nil {
		return nil
	}
	out := new(BootstrapProfileList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BootstrapProfileList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BootstrapProfileReference) DeepCopyInto(out *BootstrapProfileReference) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BootstrapProfileReference.
func (in *BootstrapProfileReference) DeepCopy() *BootstrapProfileReference {
	if in == nil {
		return nil
	}
	out := new(BootstrapProfileReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BootstrapProfileSpec) DeepCopyInto(out *BootstrapProfileSpec) {
	*out = *in
	out.Strategy = in.Strategy
	out.Defaults = in.Defaults
	if in.Artifacts != nil {
		in, out := &in.Artifacts, &out.Artifacts
		*out = make([]BootstrapArtifact, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BootstrapProfileSpec.
func (in *BootstrapProfileSpec) DeepCopy() *BootstrapProfileSpec {
	if in == nil {
		return nil
	}
	out := new(BootstrapProfileSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BootstrapProfileStatus) DeepCopyInto(out *BootstrapProfileStatus) {
	*out = *in
	out.Expansion = in.Expansion
	out.Summary = in.Summary
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BootstrapProfileStatus.
func (in *BootstrapProfileStatus) DeepCopy() *BootstrapProfileStatus {
	if in == nil {
		return nil
	}
	out := new(BootstrapProfileStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BootstrapStrategy) DeepCopyInto(out *BootstrapStrategy) {
	*out = *in
	out.TimeoutPerArtifact = in.TimeoutPerArtifact
	if in.MaxRetries != nil {
		in, out := &in.MaxRetries, &out.MaxRetries
		*out = new(int32)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BootstrapStrategy.
func (in *BootstrapStrategy) DeepCopy() *BootstrapStrategy {
	if in == nil {
		return nil
	}
	out := new(BootstrapStrategy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BootstrapSummary) DeepCopyInto(out *BootstrapSummary) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BootstrapSummary.
func (in *BootstrapSummary) DeepCopy() *BootstrapSummary {
	if in == nil {
		return nil
	}
	out := new(BootstrapSummary)
	in.DeepCopyInto(out)
	return out
}
