//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArtifactAppGroupStatus) DeepCopyInto(out *ArtifactAppGroupStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArtifactAppGroupStatus.
func (in *ArtifactAppGroupStatus) DeepCopy() *ArtifactAppGroupStatus {
	if in == nil {
		return nil
	}
	out := new(ArtifactAppGroupStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BootstrapInstallation) DeepCopyInto(out *BootstrapInstallation) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BootstrapInstallation.
func (in *BootstrapInstallation) DeepCopy() *BootstrapInstallation {
	if in == nil {
		return nil
	}
	out := new(BootstrapInstallation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BootstrapInstallation) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BootstrapInstallationList) DeepCopyInto(out *BootstrapInstallationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BootstrapInstallation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BootstrapInstallationList.
func (in *BootstrapInstallationList) DeepCopy() *BootstrapInstallationList {
	if in == nil {
		return nil
	}
	out := new(BootstrapInstallationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BootstrapInstallationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BootstrapInstallationSpec) DeepCopyInto(out *BootstrapInstallationSpec) {
	*out = *in
	out.ProfileRef = in.ProfileRef
	out.Artifact = in.Artifact
	out.Target = in.Target
	if in.DependsOn != nil {
		in, out := &in.DependsOn, &out.DependsOn
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.InstallOptions.DeepCopyInto(&out.InstallOptions)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BootstrapInstallationSpec.
func (in *BootstrapInstallationSpec) DeepCopy() *BootstrapInstallationSpec {
	if in == nil {
		return nil
	}
	out := new(BootstrapInstallationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BootstrapInstallationStatus) DeepCopyInto(out *BootstrapInstallationStatus) {
	*out = *in
	out.AppGroup = in.AppGroup
	if in.StartedAt != nil {
		in, out := &in.StartedAt, &out.StartedAt
		*out = (*in).DeepCopy()
	}
	if in.CompletedAt != nil {
		in, out := &in.CompletedAt, &out.CompletedAt
		*out = (*in).DeepCopy()
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BootstrapInstallationStatus.
func (in *BootstrapInstallationStatus) DeepCopy() *BootstrapInstallationStatus {
	if in == nil {
		return nil
	}
	out := new(BootstrapInstallationStatus)
	in.DeepCopyInto(out)
	return out
}
