//go:build !ignore_autogenerated

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import runtime "k8s.io/apimachinery/pkg/runtime"

func (in *ArtifactAppGroupStatus) DeepCopyInto(out *ArtifactAppGroupStatus) { *out = *in }
func (in *ArtifactAppGroupStatus) DeepCopy() *ArtifactAppGroupStatus {
	if in == nil {
		return nil
	}
	out := new(ArtifactAppGroupStatus)
	in.DeepCopyInto(out)
	return out
}
func (in *ArtifactReference) DeepCopyInto(out *ArtifactReference) { *out = *in }
func (in *ArtifactReference) DeepCopy() *ArtifactReference {
	if in == nil {
		return nil
	}
	out := new(ArtifactReference)
	in.DeepCopyInto(out)
	return out
}
func (in *ArtifactTarget) DeepCopyInto(out *ArtifactTarget) { *out = *in }
func (in *ArtifactTarget) DeepCopy() *ArtifactTarget {
	if in == nil {
		return nil
	}
	out := new(ArtifactTarget)
	in.DeepCopyInto(out)
	return out
}
func (in *BootstrapInstallOptions) DeepCopyInto(out *BootstrapInstallOptions) {
	*out = *in
	if in.HelmValues != nil {
		in, out := &in.HelmValues, &out.HelmValues
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}
func (in *BootstrapInstallOptions) DeepCopy() *BootstrapInstallOptions {
	if in == nil {
		return nil
	}
	out := new(BootstrapInstallOptions)
	in.DeepCopyInto(out)
	return out
}
func (in *BootstrapInstallation) DeepCopyInto(out *BootstrapInstallation) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}
func (in *BootstrapInstallation) DeepCopy() *BootstrapInstallation {
	if in == nil {
		return nil
	}
	out := new(BootstrapInstallation)
	in.DeepCopyInto(out)
	return out
}
func (in *BootstrapInstallation) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
func (in *BootstrapInstallationList) DeepCopyInto(out *BootstrapInstallationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BootstrapInstallation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}
func (in *BootstrapInstallationList) DeepCopy() *BootstrapInstallationList {
	if in == nil {
		return nil
	}
	out := new(BootstrapInstallationList)
	in.DeepCopyInto(out)
	return out
}
func (in *BootstrapInstallationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
func (in *BootstrapInstallationSpec) DeepCopyInto(out *BootstrapInstallationSpec) {
	*out = *in
	out.Strategy = in.Strategy
	out.Artifact = in.Artifact
	out.Target = in.Target
	in.InstallOptions.DeepCopyInto(&out.InstallOptions)
}
func (in *BootstrapInstallationSpec) DeepCopy() *BootstrapInstallationSpec {
	if in == nil {
		return nil
	}
	out := new(BootstrapInstallationSpec)
	in.DeepCopyInto(out)
	return out
}
func (in *BootstrapInstallationStatus) DeepCopyInto(out *BootstrapInstallationStatus) {
	*out = *in
	out.AppGroup = in.AppGroup
	if in.StartedAt != nil {
		in, out := &in.StartedAt, &out.StartedAt
		*out = (*in).DeepCopy()
	}
	if in.CompletedAt != nil {
		in, out := &in.CompletedAt, &out.CompletedAt
		*out = (*in).DeepCopy()
	}
}
func (in *BootstrapInstallationStatus) DeepCopy() *BootstrapInstallationStatus {
	if in == nil {
		return nil
	}
	out := new(BootstrapInstallationStatus)
	in.DeepCopyInto(out)
	return out
}
func (in *BootstrapStrategy) DeepCopyInto(out *BootstrapStrategy) {
	*out = *in
	out.TimeoutPerArtifact = in.TimeoutPerArtifact
	if in.MaxRetries != nil {
		in, out := &in.MaxRetries, &out.MaxRetries
		*out = new(int32)
		**out = **in
	}
}
func (in *BootstrapStrategy) DeepCopy() *BootstrapStrategy {
	if in == nil {
		return nil
	}
	out := new(BootstrapStrategy)
	in.DeepCopyInto(out)
	return out
}
