/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	cvmv1alpha1 "github.com/w7panel/w7panel/k8s/pkg/apis/cvm/v1alpha1"
	applyconfigurationcvmv1alpha1 "github.com/w7panel/w7panel/k8s/pkg/client/cvm/applyconfiguration/cvm/v1alpha1"
	scheme "github.com/w7panel/w7panel/k8s/pkg/client/cvm/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// CvmsGetter has a method to return a CvmInterface.
// A group's client should implement this interface.
type CvmsGetter interface {
	Cvms(namespace string) CvmInterface
}

// CvmInterface has methods to work with Cvm resources.
type CvmInterface interface {
	Create(ctx context.Context, cvm *cvmv1alpha1.Cvm, opts v1.CreateOptions) (*cvmv1alpha1.Cvm, error)
	Update(ctx context.Context, cvm *cvmv1alpha1.Cvm, opts v1.UpdateOptions) (*cvmv1alpha1.Cvm, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, cvm *cvmv1alpha1.Cvm, opts v1.UpdateOptions) (*cvmv1alpha1.Cvm, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*cvmv1alpha1.Cvm, error)
	List(ctx context.Context, opts v1.ListOptions) (*cvmv1alpha1.CvmList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *cvmv1alpha1.Cvm, err error)
	Apply(ctx context.Context, cvm *applyconfigurationcvmv1alpha1.CvmApplyConfiguration, opts v1.ApplyOptions) (result *cvmv1alpha1.Cvm, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, cvm *applyconfigurationcvmv1alpha1.CvmApplyConfiguration, opts v1.ApplyOptions) (result *cvmv1alpha1.Cvm, err error)
	CvmExpansion
}

// cvms implements CvmInterface
type cvms struct {
	*gentype.ClientWithListAndApply[*cvmv1alpha1.Cvm, *cvmv1alpha1.CvmList, *applyconfigurationcvmv1alpha1.CvmApplyConfiguration]
}

// newCvms returns a Cvms
func newCvms(c *CvmV1alpha1Client, namespace string) *cvms {
	return &cvms{
		gentype.NewClientWithListAndApply[*cvmv1alpha1.Cvm, *cvmv1alpha1.CvmList, *applyconfigurationcvmv1alpha1.CvmApplyConfiguration](
			"cvms",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *cvmv1alpha1.Cvm { return &cvmv1alpha1.Cvm{} },
			func() *cvmv1alpha1.CvmList { return &cvmv1alpha1.CvmList{} },
		),
	}
}
