/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	cvmv1alpha1 "github.com/w7panel/w7panel/k8s/pkg/apis/cvm/v1alpha1"
	applyconfigurationcvmv1alpha1 "github.com/w7panel/w7panel/k8s/pkg/client/cvm/applyconfiguration/cvm/v1alpha1"
	scheme "github.com/w7panel/w7panel/k8s/pkg/client/cvm/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// CvmConsoleOrdersGetter has a method to return a CvmConsoleOrderInterface.
// A group's client should implement this interface.
type CvmConsoleOrdersGetter interface {
	CvmConsoleOrders(namespace string) CvmConsoleOrderInterface
}

// CvmConsoleOrderInterface has methods to work with CvmConsoleOrder resources.
type CvmConsoleOrderInterface interface {
	Create(ctx context.Context, cvmConsoleOrder *cvmv1alpha1.CvmConsoleOrder, opts v1.CreateOptions) (*cvmv1alpha1.CvmConsoleOrder, error)
	Update(ctx context.Context, cvmConsoleOrder *cvmv1alpha1.CvmConsoleOrder, opts v1.UpdateOptions) (*cvmv1alpha1.CvmConsoleOrder, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, cvmConsoleOrder *cvmv1alpha1.CvmConsoleOrder, opts v1.UpdateOptions) (*cvmv1alpha1.CvmConsoleOrder, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*cvmv1alpha1.CvmConsoleOrder, error)
	List(ctx context.Context, opts v1.ListOptions) (*cvmv1alpha1.CvmConsoleOrderList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *cvmv1alpha1.CvmConsoleOrder, err error)
	Apply(ctx context.Context, cvmConsoleOrder *applyconfigurationcvmv1alpha1.CvmConsoleOrderApplyConfiguration, opts v1.ApplyOptions) (result *cvmv1alpha1.CvmConsoleOrder, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, cvmConsoleOrder *applyconfigurationcvmv1alpha1.CvmConsoleOrderApplyConfiguration, opts v1.ApplyOptions) (result *cvmv1alpha1.CvmConsoleOrder, err error)
	CvmConsoleOrderExpansion
}

// cvmConsoleOrders implements CvmConsoleOrderInterface
type cvmConsoleOrders struct {
	*gentype.ClientWithListAndApply[*cvmv1alpha1.CvmConsoleOrder, *cvmv1alpha1.CvmConsoleOrderList, *applyconfigurationcvmv1alpha1.CvmConsoleOrderApplyConfiguration]
}

// newCvmConsoleOrders returns a CvmConsoleOrders
func newCvmConsoleOrders(c *CvmV1alpha1Client, namespace string) *cvmConsoleOrders {
	return &cvmConsoleOrders{
		gentype.NewClientWithListAndApply[*cvmv1alpha1.CvmConsoleOrder, *cvmv1alpha1.CvmConsoleOrderList, *applyconfigurationcvmv1alpha1.CvmConsoleOrderApplyConfiguration](
			"cvmconsoleorders",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *cvmv1alpha1.CvmConsoleOrder { return &cvmv1alpha1.CvmConsoleOrder{} },
			func() *cvmv1alpha1.CvmConsoleOrderList { return &cvmv1alpha1.CvmConsoleOrderList{} },
		),
	}
}
