/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	microappv1alpha1 "github.com/w7panel/w7panel/k8s/pkg/apis/microapp/v1alpha1"
	applyconfigurationmicroappv1alpha1 "github.com/w7panel/w7panel/k8s/pkg/client/microapp/applyconfiguration/microapp/v1alpha1"
	scheme "github.com/w7panel/w7panel/k8s/pkg/client/microapp/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// MicroAppsGetter has a method to return a MicroAppInterface.
// A group's client should implement this interface.
type MicroAppsGetter interface {
	MicroApps(namespace string) MicroAppInterface
}

// MicroAppInterface has methods to work with MicroApp resources.
type MicroAppInterface interface {
	Create(ctx context.Context, microApp *microappv1alpha1.MicroApp, opts v1.CreateOptions) (*microappv1alpha1.MicroApp, error)
	Update(ctx context.Context, microApp *microappv1alpha1.MicroApp, opts v1.UpdateOptions) (*microappv1alpha1.MicroApp, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*microappv1alpha1.MicroApp, error)
	List(ctx context.Context, opts v1.ListOptions) (*microappv1alpha1.MicroAppList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *microappv1alpha1.MicroApp, err error)
	Apply(ctx context.Context, microApp *applyconfigurationmicroappv1alpha1.MicroAppApplyConfiguration, opts v1.ApplyOptions) (result *microappv1alpha1.MicroApp, err error)
	MicroAppExpansion
}

// microApps implements MicroAppInterface
type microApps struct {
	*gentype.ClientWithListAndApply[*microappv1alpha1.MicroApp, *microappv1alpha1.MicroAppList, *applyconfigurationmicroappv1alpha1.MicroAppApplyConfiguration]
}

// newMicroApps returns a MicroApps
func newMicroApps(c *MicroappV1alpha1Client, namespace string) *microApps {
	return &microApps{
		gentype.NewClientWithListAndApply[*microappv1alpha1.MicroApp, *microappv1alpha1.MicroAppList, *applyconfigurationmicroappv1alpha1.MicroAppApplyConfiguration](
			"microapps",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *microappv1alpha1.MicroApp { return &microappv1alpha1.MicroApp{} },
			func() *microappv1alpha1.MicroAppList { return &microappv1alpha1.MicroAppList{} },
		),
	}
}
