apiVersion: extensions.higress.io/v1alpha1
kind: WasmPlugin
metadata:
    annotations:
        higress.io/wasm-plugin-description: 限流管理
        higress.io/wasm-plugin-title: 限流管理
    labels:
        higress.io/wasm-plugin-name: cluster-key-rate-limit
    name: cluster-key-rate-limit
    namespace: higress-system
spec:
    defaultConfigDisable: true
    failStrategy: FAIL_OPEN
    phase: UNSPECIFIED_PHASE
    priority: 20
    url: >-
        oci://higress-registry.cn-hangzhou.cr.aliyuncs.com/plugins/cluster-key-rate-limit:1.0.0