/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// MenuApplyConfiguration represents a declarative configuration of the Menu type for use
// with apply.
type MenuApplyConfiguration struct {
	Displayorder *int    `json:"displayorder,omitempty"`
	Do           *string `json:"do,omitempty"`
	Icon         *string `json:"icon,omitempty"`
	IsDefault    *int    `json:"is_default,omitempty"`
	Location     *string `json:"location,omitempty"`
	Title        *string `json:"title,omitempty"`
	Parent       *string `json:"parent,omitempty"`
}

// MenuApplyConfiguration constructs a declarative configuration of the Menu type for use with
// apply.
func Menu() *MenuApplyConfiguration {
	return &MenuApplyConfiguration{}
}

// WithDisplayorder sets the Displayorder field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Displayorder field is set to the value of the last call.
func (b *MenuApplyConfiguration) WithDisplayorder(value int) *MenuApplyConfiguration {
	b.Displayorder = &value
	return b
}

// WithDo sets the Do field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Do field is set to the value of the last call.
func (b *MenuApplyConfiguration) WithDo(value string) *MenuApplyConfiguration {
	b.Do = &value
	return b
}

// WithIcon sets the Icon field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Icon field is set to the value of the last call.
func (b *MenuApplyConfiguration) WithIcon(value string) *MenuApplyConfiguration {
	b.Icon = &value
	return b
}

// WithIsDefault sets the IsDefault field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IsDefault field is set to the value of the last call.
func (b *MenuApplyConfiguration) WithIsDefault(value int) *MenuApplyConfiguration {
	b.IsDefault = &value
	return b
}

// WithLocation sets the Location field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Location field is set to the value of the last call.
func (b *MenuApplyConfiguration) WithLocation(value string) *MenuApplyConfiguration {
	b.Location = &value
	return b
}

// WithTitle sets the Title field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Title field is set to the value of the last call.
func (b *MenuApplyConfiguration) WithTitle(value string) *MenuApplyConfiguration {
	b.Title = &value
	return b
}

// WithParent sets the Parent field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Parent field is set to the value of the last call.
func (b *MenuApplyConfiguration) WithParent(value string) *MenuApplyConfiguration {
	b.Parent = &value
	return b
}
