/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// MicroAppSpecApplyConfiguration represents a declarative configuration of the MicroAppSpec type for use
// with apply.
type MicroAppSpecApplyConfiguration struct {
	Framework   *string                            `json:"framework,omitempty"`
	BackendUrl  *string                            `json:"backendUrl,omitempty"`
	FrontendUrl *string                            `json:"frontendUrl,omitempty"`
	ProxyUrl    *string                            `json:"proxyUrl,omitempty"`
	Title       *string                            `json:"title,omitempty"`
	Logo        *string                            `json:"logo,omitempty"`
	Config      *MicroAppConfigApplyConfiguration  `json:"config,omitempty"`
	Version     *string                            `json:"version,omitempty"`
	ConfigV2    *MicroAppConfig2ApplyConfiguration `json:"config-v2,omitempty"`
	Description *string                            `json:"description,omitempty"`
	Bindings    []BindingsApplyConfiguration       `json:"bindings,omitempty"`
}

// MicroAppSpecApplyConfiguration constructs a declarative configuration of the MicroAppSpec type for use with
// apply.
func MicroAppSpec() *MicroAppSpecApplyConfiguration {
	return &MicroAppSpecApplyConfiguration{}
}

// WithFramework sets the Framework field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Framework field is set to the value of the last call.
func (b *MicroAppSpecApplyConfiguration) WithFramework(value string) *MicroAppSpecApplyConfiguration {
	b.Framework = &value
	return b
}

// WithBackendUrl sets the BackendUrl field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BackendUrl field is set to the value of the last call.
func (b *MicroAppSpecApplyConfiguration) WithBackendUrl(value string) *MicroAppSpecApplyConfiguration {
	b.BackendUrl = &value
	return b
}

// WithFrontendUrl sets the FrontendUrl field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the FrontendUrl field is set to the value of the last call.
func (b *MicroAppSpecApplyConfiguration) WithFrontendUrl(value string) *MicroAppSpecApplyConfiguration {
	b.FrontendUrl = &value
	return b
}

// WithProxyUrl sets the ProxyUrl field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ProxyUrl field is set to the value of the last call.
func (b *MicroAppSpecApplyConfiguration) WithProxyUrl(value string) *MicroAppSpecApplyConfiguration {
	b.ProxyUrl = &value
	return b
}

// WithTitle sets the Title field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Title field is set to the value of the last call.
func (b *MicroAppSpecApplyConfiguration) WithTitle(value string) *MicroAppSpecApplyConfiguration {
	b.Title = &value
	return b
}

// WithLogo sets the Logo field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Logo field is set to the value of the last call.
func (b *MicroAppSpecApplyConfiguration) WithLogo(value string) *MicroAppSpecApplyConfiguration {
	b.Logo = &value
	return b
}

// WithConfig sets the Config field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Config field is set to the value of the last call.
func (b *MicroAppSpecApplyConfiguration) WithConfig(value *MicroAppConfigApplyConfiguration) *MicroAppSpecApplyConfiguration {
	b.Config = value
	return b
}

// WithVersion sets the Version field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Version field is set to the value of the last call.
func (b *MicroAppSpecApplyConfiguration) WithVersion(value string) *MicroAppSpecApplyConfiguration {
	b.Version = &value
	return b
}

// WithConfigV2 sets the ConfigV2 field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ConfigV2 field is set to the value of the last call.
func (b *MicroAppSpecApplyConfiguration) WithConfigV2(value *MicroAppConfig2ApplyConfiguration) *MicroAppSpecApplyConfiguration {
	b.ConfigV2 = value
	return b
}

// WithDescription sets the Description field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Description field is set to the value of the last call.
func (b *MicroAppSpecApplyConfiguration) WithDescription(value string) *MicroAppSpecApplyConfiguration {
	b.Description = &value
	return b
}

// WithBindings adds the given value to the Bindings field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Bindings field.
func (b *MicroAppSpecApplyConfiguration) WithBindings(values ...*BindingsApplyConfiguration) *MicroAppSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithBindings")
		}
		b.Bindings = append(b.Bindings, *values[i])
	}
	return b
}
