/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// ProxyRequestApplyConfiguration represents a declarative configuration of the ProxyRequest type for use
// with apply.
type ProxyRequestApplyConfiguration struct {
	Headers map[string]string `json:"headers,omitempty"`
	Query   map[string]string `json:"query,omitempty"`
}

// ProxyRequestApplyConfiguration constructs a declarative configuration of the ProxyRequest type for use with
// apply.
func ProxyRequest() *ProxyRequestApplyConfiguration {
	return &ProxyRequestApplyConfiguration{}
}

// WithHeaders puts the entries into the Headers field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Headers field,
// overwriting an existing map entries in Headers field with the same key.
func (b *ProxyRequestApplyConfiguration) WithHeaders(entries map[string]string) *ProxyRequestApplyConfiguration {
	if b.Headers == nil && len(entries) > 0 {
		b.Headers = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.Headers[k] = v
	}
	return b
}

// WithQuery puts the entries into the Query field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Query field,
// overwriting an existing map entries in Query field with the same key.
func (b *ProxyRequestApplyConfiguration) WithQuery(entries map[string]string) *ProxyRequestApplyConfiguration {
	if b.Query == nil && len(entries) > 0 {
		b.Query = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.Query[k] = v
	}
	return b
}
