/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// RoleApplyConfiguration represents a declarative configuration of the Role type for use
// with apply.
type RoleApplyConfiguration struct {
	LoadMode      *string                         `json:"load_mode,omitempty"`
	ProxyRequest  *ProxyRequestApplyConfiguration `json:"proxy_request,omitempty"`
	FrontendProps map[string]string               `json:"frontend_props,omitempty"`
	ServerUrl     *string                         `json:"serverUrl,omitempty"`
}

// RoleApplyConfiguration constructs a declarative configuration of the Role type for use with
// apply.
func Role() *RoleApplyConfiguration {
	return &RoleApplyConfiguration{}
}

// WithLoadMode sets the LoadMode field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LoadMode field is set to the value of the last call.
func (b *RoleApplyConfiguration) WithLoadMode(value string) *RoleApplyConfiguration {
	b.LoadMode = &value
	return b
}

// WithProxyRequest sets the ProxyRequest field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ProxyRequest field is set to the value of the last call.
func (b *RoleApplyConfiguration) WithProxyRequest(value *ProxyRequestApplyConfiguration) *RoleApplyConfiguration {
	b.ProxyRequest = value
	return b
}

// WithFrontendProps puts the entries into the FrontendProps field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the FrontendProps field,
// overwriting an existing map entries in FrontendProps field with the same key.
func (b *RoleApplyConfiguration) WithFrontendProps(entries map[string]string) *RoleApplyConfiguration {
	if b.FrontendProps == nil && len(entries) > 0 {
		b.FrontendProps = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.FrontendProps[k] = v
	}
	return b
}

// WithServerUrl sets the ServerUrl field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ServerUrl field is set to the value of the last call.
func (b *RoleApplyConfiguration) WithServerUrl(value string) *RoleApplyConfiguration {
	b.ServerUrl = &value
	return b
}
