/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	gpuclassv1alpha1 "github.com/w7panel/w7panel/k8s/pkg/apis/gpuclass/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// GpuClassLister helps list GpuClasses.
// All objects returned here must be treated as read-only.
type GpuClassLister interface {
	// List lists all GpuClasses in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*gpuclassv1alpha1.GpuClass, err error)
	// GpuClasses returns an object that can list and get GpuClasses.
	GpuClasses(namespace string) GpuClassNamespaceLister
	GpuClassListerExpansion
}

// gpuClassLister implements the GpuClassLister interface.
type gpuClassLister struct {
	listers.ResourceIndexer[*gpuclassv1alpha1.GpuClass]
}

// NewGpuClassLister returns a new GpuClassLister.
func NewGpuClassLister(indexer cache.Indexer) GpuClassLister {
	return &gpuClassLister{listers.New[*gpuclassv1alpha1.GpuClass](indexer, gpuclassv1alpha1.Resource("gpuclass"))}
}

// GpuClasses returns an object that can list and get GpuClasses.
func (s *gpuClassLister) GpuClasses(namespace string) GpuClassNamespaceLister {
	return gpuClassNamespaceLister{listers.NewNamespaced[*gpuclassv1alpha1.GpuClass](s.ResourceIndexer, namespace)}
}

// GpuClassNamespaceLister helps list and get GpuClasses.
// All objects returned here must be treated as read-only.
type GpuClassNamespaceLister interface {
	// List lists all GpuClasses in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*gpuclassv1alpha1.GpuClass, err error)
	// Get retrieves the GpuClass from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*gpuclassv1alpha1.GpuClass, error)
	GpuClassNamespaceListerExpansion
}

// gpuClassNamespaceLister implements the GpuClassNamespaceLister
// interface.
type gpuClassNamespaceLister struct {
	listers.ResourceIndexer[*gpuclassv1alpha1.GpuClass]
}
