/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	microappsettingv1alpha1 "github.com/w7panel/w7panel/k8s/pkg/apis/microappsetting/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// MicroAppSettingLister helps list MicroAppSettings.
// All objects returned here must be treated as read-only.
type MicroAppSettingLister interface {
	// List lists all MicroAppSettings in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*microappsettingv1alpha1.MicroAppSetting, err error)
	// MicroAppSettings returns an object that can list and get MicroAppSettings.
	MicroAppSettings(namespace string) MicroAppSettingNamespaceLister
	MicroAppSettingListerExpansion
}

// microAppSettingLister implements the MicroAppSettingLister interface.
type microAppSettingLister struct {
	listers.ResourceIndexer[*microappsettingv1alpha1.MicroAppSetting]
}

// NewMicroAppSettingLister returns a new MicroAppSettingLister.
func NewMicroAppSettingLister(indexer cache.Indexer) MicroAppSettingLister {
	return &microAppSettingLister{listers.New[*microappsettingv1alpha1.MicroAppSetting](indexer, microappsettingv1alpha1.Resource("microappsetting"))}
}

// MicroAppSettings returns an object that can list and get MicroAppSettings.
func (s *microAppSettingLister) MicroAppSettings(namespace string) MicroAppSettingNamespaceLister {
	return microAppSettingNamespaceLister{listers.NewNamespaced[*microappsettingv1alpha1.MicroAppSetting](s.ResourceIndexer, namespace)}
}

// MicroAppSettingNamespaceLister helps list and get MicroAppSettings.
// All objects returned here must be treated as read-only.
type MicroAppSettingNamespaceLister interface {
	// List lists all MicroAppSettings in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*microappsettingv1alpha1.MicroAppSetting, err error)
	// Get retrieves the MicroAppSetting from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*microappsettingv1alpha1.MicroAppSetting, error)
	MicroAppSettingNamespaceListerExpansion
}

// microAppSettingNamespaceLister implements the MicroAppSettingNamespaceLister
// interface.
type microAppSettingNamespaceLister struct {
	listers.ResourceIndexer[*microappsettingv1alpha1.MicroAppSetting]
}
